package.json
src/components/Icons/CollapseLeftIcon/CollapseLeftIcon.stories.tsx
src/components/Icons/CollapseLeftIcon/CollapseLeftIcon.tsx
src/components/Icons/CollapseLeftIcon/index.ts
src/components/Icons/CollapseRightIcon/CollapseRightIcon.stories.tsx
src/components/Icons/CollapseRightIcon/CollapseRightIcon.tsx
src/components/Icons/CollapseRightIcon/index.ts

Because
- Collapsable sidebar need two more icon: CollapseRight/Left
This commit
- Add CollapseRight/Left icon

feat: add sidebar related icon

---

package.json
src/components/ToggleFields/StatefulToggleField/index.ts
src/components/ToggleFields/index.ts

Because
- Last commit didn't properly export stateful toggle field
This commit
- properly export stateful toggle field

feat: export stateful toggle field

---

package.json
src/components/ToggleFields/BasicToggleField/BasicToggleField.stories.tsx
src/components/ToggleFields/BasicToggleField/BasicToggleField.tsx
src/components/ToggleFields/StatefulToggleField/StatefulToggleField.stories.tsx
src/components/ToggleFields/StatefulToggleField/StatefulToggleField.tsx
src/components/ToggleFields/ToggleFieldBase/ToggleFieldBase.stories.tsx
src/components/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx

Because
- Toggle field's value and defaultChecked had conflict
This commit
- Deprecate defaultChecked

chore: deprecate toggle field's defaultChecked prop

---

package.json
src/components/TextWithHtml/TextWithHtml.tsx

Because
- TextWithHtml import the wrong react path
This commit

fix: fix react is not defined issue

---

src/components/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.stories.tsx
src/components/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.tsx
src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.stories.tsx
src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx

Because
- Progress message box should return null if the message is null or undefinded
This commit
- Refactor ProgressMessageBox

refactor: refactor ProgressMessageBox

---

package.json
src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx

Because
- Progress message box's status can be nullable
This commit
- Make progress message box status nullable

feat: make progress message box status nullable

---

package.json
src/components/Icons/ArtiVcIcon/ArtiVcIcon.stories.tsx
src/components/Icons/ArtiVcIcon/ArtiVcIcon.tsx

Because
- ArtiVC's prop has unnecessary prop: color
This commit
- Remove color prop at ArtiVC icon

fix: fix artivc props type

---

package.json
src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx
src/ui/Buttons/OutlineButton/OutlineButton.tsx
src/ui/Buttons/SolidButton/SolidButton.tsx

Because
- New button components' react are not defined
This commit

fix: fix react not defined issue

---

package.json
src/types/general.ts
src/ui/InputLabels/InputLabelBase/InputLabelBase.tsx
src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx
src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
src/ui/TextAreas/BasicTextArea/BasicTextArea.stories.tsx
src/ui/TextAreas/BasicTextArea/BasicTextArea.tsx
src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
src/ui/TextFields/BasicTextField/BasicTextField.stories.tsx
src/ui/TextFields/BasicTextField/BasicTextField.tsx
src/ui/TextFields/ProtectedBasicTextField/ProtectedBasicTextField.stories.tsx
src/ui/TextFields/ProtectedBasicTextField/ProtectedBasicTextField.tsx
src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
src/ui/ToggleFields/BasicToggleField/BasicToggleField.stories.tsx
src/ui/ToggleFields/BasicToggleField/BasicToggleField.tsx
src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.stories.tsx
src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.tsx
src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.stories.tsx
src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
src/ui/UploadFileFields/BasicUploadFileField/BasicUploadFileField.stories.tsx
src/ui/UploadFileFields/BasicUploadFileField/BasicUploadFileField.tsx
src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.stories.tsx
src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx

- Before this change, we only accept pre-defined props. For example, the component below can't have onBlur (JSX props) to it.
```js
<BasicSingleSelect
id="autocomplete-with-icon"
instanceId="autocomplete-with-icon"
onChange={onChange}
options={options}
label="autocomplete-with-icon"
/>
```
- After this change, we could safely pass JSX prop into our component
```js
<BasicSingleSelect
id="autocomplete-with-icon"
instanceId="autocomplete-with-icon"
onChange={onChange}
options={options}
label="autocomplete-with-icon"
onBlur={onBlurHandler}
/>
```
- Replace our defined props with JSX props at InputField
- Rename onChangeInput to onChange

feat: accept additional JSX props at regular input field

---

package.json
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx

Because
- Input field onChange prop should be optional
This commit
- Make inputField onChange optional

feat: make inputField onChange optional

---

package.json
src/ui/Logo/index.ts

Because
- VdpLogoProps is not correctly exported
This commit
- Export VdpLogoProps

fix: fix VdpLogoProps is not correctly exported

---

package.json
src/ui/Icons/IconBase/IconBase.tsx

Because
- IconBase position prop should be optional
This commit
- Make IconBase position prop be optional

feat: make IconBase position prop be optional

---

package.json
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx

Because
- We need data-testid to make our test selector stable
This commit
- add test id into basic select base

feat: add test id into basic select base

---

package.json
src/ui/Buttons/ButtonBase/ButtonBase.tsx
src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx
src/ui/Buttons/OutlineButton/OutlineButton.stories.tsx
src/ui/Buttons/OutlineButton/OutlineButton.tsx
src/ui/Buttons/SolidButton/SolidButton.tsx
src/ui/Buttons/TextButton/TextButton.stories.tsx
src/ui/Buttons/TextButton/TextButton.tsx

Because
- We use itemGapX in button that is misleading
This commit
- rename button props from itemGapX to itemSpaceX

chore: rename button props

---

package.json
src/ui/Buttons/ButtonBase/ButtonBase.tsx
src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx
src/ui/Buttons/OutlineButton/OutlineButton.stories.tsx
src/ui/Buttons/OutlineButton/OutlineButton.tsx
src/ui/Buttons/SolidButton/SolidButton.tsx
src/ui/Buttons/TextButton/TextButton.stories.tsx
src/ui/Buttons/TextButton/TextButton.tsx

Because
- Tailwind support gap on flexbox now https://tailwindcss.com/docs/gap
- We need a way to control button text size
This commit
- Add textSize prop on Button
- Roll back to itemGapX on Buttons

feat: add textSize prop and roll back to itemGapX on Buttons

---

package.json
src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx

In order to utilize focus and blur events to handle more corner cases of SingleSelect component. This commit exposes onBlur and onFocus event handlers as props

feat: expose blur/focus event of select

---

package.json
src/utils/index.ts

This commit accepts HTMLElement and Element as input props of getElementPosition to make it more versatile.

feat: expand the functionality of getElementPosition to accept Element parameter

---

src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.stories.tsx
src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.tsx

Because
- We need a way to customize the loading label text of StatefulToggleField
This commit
- expose loadingLabelText props at StatefulToggleField

feat: expose loadingLabelText props at StatefulToggleField

---

package.json
src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.tsx

Because
- In StateFulToggleField we use {...props} to spread the props but there had a prop "labelLoadingText" that won't be directly used as react component props. We need to catch it first. 
```js
{labelLoadingText, ...remaingProps} = props
```
This commit
- fix redundant react prop issue

fix: fix redundant react prop issue

---

src/ui/Accordion/AccordionBase/AccordionBase.stories.tsx
src/ui/Accordion/BasicAccordion/BasicAccordion.stories.tsx
src/ui/Accordion/BgIconAccordion/BgIconAccordion.stories.tsx

Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline

chore: rename Visual Data Preparation to Versatile Data Pipeline

---

package.json
src/toolkits/getModelDefinitionToolkit.tsx
src/toolkits/index.ts
src/types/general.ts

Because
- We want to centralize some ui component related toolkit into design-system
This commit
- add getModelDefinitionToolkit

feat: add getModelDefinitionToolkit

---

package.json
src/toolkits/getPipelineModeToolkit.tsx
src/toolkits/index.ts
src/types/general.ts

Because
- We want to centralize some ui component related toolkit into design-system
This commit
- add getPipelineModeToolkit

feat: getPipelineModeToolkit

---

package.json
src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx

Because
- Our react-select's menu z-index is wrong
This commit
- fix react select zindex issue

fix: fix react select zindex issue

---

.changeset/lovely-files-taste.md
packages/ui/package.json

Because
- The npm publish encounters private lib not allowed issue
This commit
- update package config to let npm know this is public lib

feat: update package config

---

.changeset/forty-crabs-wink.md
packages/eslint-config-cortex/package.json

Because
- the name is wrong
This commit
- update eslint-config-cortex package name to @instil-ai/eslint-config-cortex

feat: update eslint-config-cortex package name

---

packages/toolkit/package.json

Because
- package toolkit's package config is wrong which cause error when publish to npm registry
This commit
-  fix toolkit package config

fix: fix toolkit package config

---

packages/toolkit/README.md
packages/toolkit/src/react-query-service/connector/destination/useDestinationDefinitions.ts
packages/toolkit/src/react-query-service/connector/destination/useDestinations.ts
packages/toolkit/src/react-query-service/connector/source/useSourceDefinitions.ts
packages/toolkit/src/react-query-service/connector/source/useSources.ts
packages/toolkit/src/react-query-service/model/useModelDefinitions.ts
packages/toolkit/src/react-query-service/model/useModelInstances.ts
packages/toolkit/src/react-query-service/model/useModelWithInstances.ts
packages/toolkit/src/react-query-service/model/useModels.ts
packages/toolkit/src/react-query-service/model/useModelsInstances.ts
packages/toolkit/src/react-query-service/model/useModelsWithInstances.ts
packages/toolkit/src/react-query-service/pipeline/usePipelines.ts
packages/toolkit/src/utility/config.ts

Because
- we need to expose important variable as env variable
This commit
- expose page size config as env NEXT_PUBLIC_QUERY_PAGE_SIZE

feat: expose page size config as env NEXT_PUBLIC_QUERY_PAGE_SIZE

---

packages/toolkit/src/store/useConfigurePipelineStore.ts

Because
- centralize the components and functions to cortex
This commit
-  add configure pipeline store to toolkit

feat: add configure pipeline store to toolkit

---

packages/toolkit/src/store/useConfigurePipelineFormStore.ts

Because
- the configurePipelineFormSchema need a field to represent the edit status
This commit
- add canEdit field into configurePipelineFormSchema

feat: add canEdit field into configurePipelineFormSchema

---

packages/toolkit/src/index.ts

Because
- the hook export path is wrong
This commit
- fix hook export path

fix: fix hook export path

---

packages/design-system/src/ui/ModalRoot.tsx

Because
- the modal root name is wrong
This commit
- fix modal root name

fix: fix modal root name

---

packages/toolkit/src/store/index.ts
packages/toolkit/src/store/useMessageBoxStore.tsx

Because
- the export path of useMessageBoxStore is wrong
- the variable name of useMessageBoxStore is wrong
This commit
- fix useMessageBoxStore export path and variable name

fix: fix useMessageBoxStore export path

---

packages/design-system/src/ui/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.stories.tsx
packages/design-system/src/ui/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.tsx
packages/design-system/src/ui/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.stories.tsx
packages/design-system/src/ui/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx

Because
- setState is too generic, we want to be as specific as possible
This commit
- replace the props of ProgressMessageBoxBase from setState to setActivate

feat: replace the props of ProgressMessageBoxBase from setState to setActivate

---

packages/toolkit/src/store/useMessageBoxStore.tsx

Because
- the update method of useMessageBoxStore is not flexible
This commit
- refactor how we update useMessageBoxStore state

refactor: refactor how we update useMessageBoxStore state

---

packages/toolkit/esbuild.js
packages/toolkit/package.json

Because
- We leave the code spilt later
This commit
- make the export path of toolkit simple

feat: make the export path of toolkit simple

---

packages/toolkit/esbuild.js
packages/toolkit/package.json
packages/toolkit/tsconfig.json

Because
- how we build `toolkit` may be wrong
This commit
- fix how we build our package

fix: fix how we build our package

---

packages/design-system/package.json

Because
- the export path of design system is wrong
This commit
- fix design-system export path

fix: fix design-system export path

---

packages/design-system/src/ui/InputLabels/InputLabelBase/InputLabelBase.tsx

Because
- The label should be null when its value is null
This commit
- fix wrong label UI when its value is null

fix: fix wrong label UI when its value is null

---

packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
packages/design-system/src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
packages/design-system/src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
packages/design-system/src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
packages/design-system/src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx

Because
- the InputField had unnecessary gap between the label and the input when the label's value is null
This commit
- fix unnecessary gap when the label value is null

fix: fix unnecessary gap when the label value is null

---

packages/design-system/package.json
packages/toolkit/package.json

Because
- The main field in the `toolkit` and the `design-system` is in-correct
This commit
- fix package.json main field in both package

fix: fix package.json main field

---

packages/design-system/.eslintrc.cjs
packages/design-system/tsconfig.json

Because
- design-system tsconfig didn't exclude test related file
This commit
- fix design-system tsconfig didn't exclude test related file

fix: fix design-system tsconfig didn't exclude test related file

---

packages/toolkit/src/lib/hook/useOnScreen.ts

Because
- centralize hooks into `toolkit`
This commit
- add useOnScreen hook

feat: add useOnScreen hook

---

packages/toolkit/src/lib/hook/index.ts

Because
- useOnScreen export path is wrong
This commit
- fix useOnScreen export path

fix: fix useOnScreen export path

---

packages/toolkit/src/lib/vdp-sdk/types.ts

Because
- centralize type definition
This commit
- add ResourceState into toolkit

feat: add ResourceState into toolkit

---

packages/toolkit/src/lib/type/index.ts

Because
- apiRoute export type is wrong
This commit
- fix apiRoute type export path

fix: fix apiRoute type export path

---

packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx
packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
packages/design-system/src/ui/SingleSelects/SingleSelectBase/SelectItem.tsx
packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx

Because
- select should not need to specify width
This commit
- make select take dynamic width

feat: make select take dynamic width

---

packages/toolkit/src/lib/react-query-service/index.ts
packages/toolkit/src/lib/vdp-sdk/helper/createInstillAxiosClient.ts

Because
- The way we set the authorization header is in-correct
This commit
- fix authorization header issue

fix: fix authorization header issue

---

packages/toolkit/src/lib/store/useCreateResourceFormStore.ts

Because
-  zod didn't correctly infer File type
This commit
- Fix Zod File type

fix: fix Zod File type

---

packages/design-system/package.json
packages/toolkit/package.json

Because
- exports property in package.json is troublesome
This commit
- remove exports property in package.json

fix: remove exports property in package.json

---

packages/toolkit/src/lib/react-query-service/index.ts

Because
- export necessary function from react-query
This commit
- export useQuery, useQueries, useMutation, useQueryClient

feat: export necessary function from react-query

---

packages/toolkit/src/lib/store/useConfigureProfileFormStore.tsx
packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts
packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileForm.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/FirstNameField.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/LastNameField.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/NewsletterSubscriptionField.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/OrgNameField.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
packages/toolkit/src/view/mgmt/ConfigureProfileForm/UserNameField.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/PipelineDescriptionField.tsx

Because
- digest user object in the configure profile form to make the form display current user info
This commit
- digest user object in the configure profile form

feat: digest user in configure profile form

---

packages/design-system/src/ui/InputLabels/InputLabelBase/InputLabelBase.tsx

Because
- we need this data-testid for testing
This commit
- add data-testid for input label

feat: add data-testid for input label

---

packages/toolkit/src/components/ModelDefinitionLabel.tsx
packages/toolkit/src/components/index.ts

Because
- We need model definition label
This commit
- add ModelDefinitionLabel

feat: add ModelDefinitionLabel

---

packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx

Because
- CreatePipelineForm doesn't handle mode selection correctly
This commit
- fix create pipeline form issue

fix: fix create pipeline form not correctly handle mode selection issue

---

packages/toolkit/src/components/DeleteResourceModal.tsx
packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
packages/toolkit/src/view/model/ConfigureModelForm.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx

Because
- delete resource modal didn't close right after user confirmation
This commit
- fix delete resource modal not close right after confirmation

fix: fix delete resource modal not close right after confirmation

---

packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
packages/toolkit/src/view/model/ConfigureModelForm.tsx
packages/toolkit/src/view/model/CreateModelForm.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceForm.tsx

Because
- let the consumers choose whether they want to disable user action or not
This commit
- expose disableDelete and disableConfigure props

feat: expose disableDelete and disableConfigure props

---

packages/toolkit/src/view/destination/DestinationsTable.tsx
packages/toolkit/src/view/model/ModelsTable.tsx
packages/toolkit/src/view/source/SourcesTable.tsx

Because
- model/source/destination head title are wrong
This commit
- fix wrong model/source/destination table head title

fix: fix wrong model/source/destination table head title

---

packages/toolkit/src/lib/utility/cookie.ts

Because
- setCookie should be more flexible
This commit
- expose secure props on setCookie

fix: expose secure props on setCookie

---

packages/toolkit/src/lib/vdp-sdk/helper/createInstillAxiosClient.ts

Because
- the axios client base url didn't use server side API base url
This commit
- fix axios client base url

fix: fix axios client base url

---

packages/toolkit/src/lib/store/useConfigureModelFormStore.ts
packages/toolkit/src/lib/store/useConfigurePipelineFormStore.ts
packages/toolkit/src/lib/store/useConfigureProfileFormStore.tsx
packages/toolkit/src/lib/store/useConfigureSourceFormStore.ts
packages/toolkit/src/lib/store/useCreateResourceFormStore.ts

Because
- form store should be dirty once the form's value change
This commit
- force form store to be dirty once there has value changed

fix: force form store to be dirty once there has value changed

---

packages/toolkit/src/lib/hook/useStateOverviewCounts.ts
packages/toolkit/src/view/destination/DestinationsTable.tsx
packages/toolkit/src/view/model/ModelsTable.tsx
packages/toolkit/src/view/pipeline/PipelinesTable.tsx
packages/toolkit/src/view/source/SourcesTable.tsx

Because
- state overview doesn't count the watch state
This commit
- fix state overview

fix: fix state overview

---

packages/toolkit/src/view/model/ChangeModelStateToggle.tsx
packages/toolkit/src/view/pipeline/ChangePipelineStateToggle.tsx

Because
- ToggelButton of resource state should have a way to be disabled
This commit
-  add disabled props into toggle button

fix: add disabled props into toggle button

---

packages/toolkit/src/view/model/ConfigureModelForm.tsx

Because
- ConfigureModelForm accessToken prop is not present
This commit
- fix ConfigureModelForm prop

fix: fix ConfigureModelForm prop

---

packages/toolkit/src/lib/react-query-service/index.ts

Because
- We need Hydrate component to operate react-query on SSR
This commit
- export Hydrate component

feat: export Hydrate component

---

packages/toolkit/src/lib/react-query-service/index.ts

Because
- we need react-query dehydrate
This commit
- export dehydrate

feat: export dehydrate

---

packages/toolkit/src/lib/react-query-service/index.ts

Because
- we didn't export DehydratedState
This commit
- export DehydratedState

fix: export DehydratedState

---

packages/toolkit/src/view/destination/DestinationsTable.tsx
packages/toolkit/src/view/model/ModelsTable.tsx
packages/toolkit/src/view/pipeline/PipelineTable.tsx
packages/toolkit/src/view/pipeline/PipelinesTable.tsx
packages/toolkit/src/view/source/SourcesTable.tsx

Because
- we should not handle delayed loading inside the component
This commit
- rollback delayed loading inside the component

fix: rollback delayed loading inside the component

---

packages/toolkit/src/view/source/SourcesTable.tsx

Because
- SourcesTable search field is wrongly disabled
This commit
- fix SourcesTable search field is wrongly disabled

fix: fix SourcesTable search field is wrongly disabled

---

packages/toolkit/src/lib/react-query-service/mgmt/useUpdateUser.ts
packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts

Because
- make function name consistent
This commit
- rename updateLocalUserMutation to updateUserMutation

feat: rename updateLocalUserMutation to updateUserMutation

---

apps/cortex-playground/src/pages/create-model.tsx
packages/toolkit/src/view/destination/CreateDestinationForm.tsx
packages/toolkit/src/view/model/CreateModelForm.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SelectExistingDestinationFlow.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx

Because
- query inside of the components like toolkit's form will make controlling the auth harder
This commit
- remove interior query

feat: remove interior query

---

packages/toolkit/src/view/destination/CreateDestinationForm.tsx
packages/toolkit/src/view/model/CreateModelForm.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SelectExistingDestinationFlow.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx

Because
- we don't want to query data upfront
This commit
- rollback to old createPipelineForm and add enabledQuery argument

feat: rollback to old createPipelineForm and add enabledQuery argument

---

packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx

Because
- We need visual hint to make test stable
This commit
- fix setup destination step hint not implemented issue

fix: fix setup destination step hint not implemented

---

packages/toolkit/src/lib/react-query-service/mgmt/index.ts

Because
- we didn't correctly export useDeleteApiToken and useApiToken
This commit
- fix missing export of apiToken related query

fix: fix missing export of apiToken related query

---

packages/toolkit/src/lib/vdp-sdk/helper/getQueryString.test.ts
packages/toolkit/src/lib/vdp-sdk/helper/getQueryString.ts

Because
- getQueryString function is wrong, it uses pageToken and pageSize instead of page_token and page_size
This commit
- fix wrong getQueryString function

fix: fix wrong getQueryString function

---

packages/toolkit/src/view/pipeline/ChangePipelineStateToggle.tsx

Because
- ChangePipelineStateToggleProps is wrong
This commit
- fix ChangePipelineStateToggleProps

fix: fix ChangePipelineStateToggleProps

---

packages/toolkit/package.json
packages/toolkit/src/lib/amplitude/helper.ts
packages/toolkit/src/lib/amplitude/type.ts
pnpm-lock.yaml

Because
- Amplitude has several new function, we would like to test it out
This commit
- In this PR we enable amplitude pageViews and sessions tracking by default
- Add several event types
```ts
| "go_to_stripe_portal"
| "go_to_stripe_checkout"
| "submit_onboarding_form"
| "change_user_info"
| "create_api_token"
| "delete_api_token";
```

feat: update amplitude config and enable pageViews and Sessions tracking

---

packages/toolkit/src/lib/react-query-service/index.ts

Because
- We need UseQueryResult and UseMutationResult type
This commit
- export UseQueryResult and UseMutationResult

feat: export UseQueryResult and UseMutationResult

---

packages/toolkit/README.md
packages/toolkit/src/lib/vdp-sdk/helper/createInstillAxiosClient.ts

Because
- We need CF header for staging SSR to work
This commit
- add CF header for staging

feat: add CF header for staging

---

packages/toolkit/src/view/model/ModelsTable.tsx

Because
- We should AI task instead of Model Task
This commit
- update ModelsTable head from Model task to AI task

chore: update ModelsTable head from Model task to AI task

---

packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx

Because
- we should not check username is exist if the username is the same
This commit
- fix configure profile form wrongly check user id

fix: fix configure profile form wrongly check user id

---

packages/toolkit/src/lib/vdp-sdk/model/helper.ts
packages/toolkit/src/view/model/CreateModelForm.tsx
packages/toolkit/src/view/model/ModelConfigurationFields.tsx

Because
- "The name of a public GitHub repository, e.g. instill-ai/model-mobilenetv2." no longer available. Need to change to instill-ai/model-mobilenetv2-dvc.
This commit
-  fix model repo description typo

fix: [INS-700] fix model repo description typo

---

packages/toolkit/package.json
packages/toolkit/src/lib/react-query-service/connector/destination/prefetchDestinations.ts
packages/toolkit/src/lib/react-query-service/connector/source/prefetchSources.ts
packages/toolkit/src/lib/react-query-service/model/prefetchModels.ts
packages/toolkit/src/lib/react-query-service/pipeline/prefetchPipelines.ts
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx

Because
- prefetch function should digest queryClient from outside
This commit
-  fix prefetch wrongly use queryClient

fix: fix prefetch wrongly use queryClient

---

packages/toolkit/src/components/cells/ModelsCell.tsx

Because
- The ModelsCell didn't correctly get the modelName
This commit
- fix modelsCell takes wrong field as modelName

fix: fix ModelsCell takes wrong field as modelName

---

packages/design-tokens/tokens/$metadata.json
packages/design-tokens/tokens/$themes.json
packages/design-tokens/tokens/semantic/comp.json
packages/design-tokens/tokens/theme/dark.json

Because
- Add first iteration of dark theme
- move the shadow tokens from light and dark colour tokens to semantic/comp
This commit
- add dark theme v1
- move shadows to semantic/comp

add dark theme v1 and move shadows to semantic/comp

---

.github/workflows/release.yml

Because
- We need to publish design-tokens to NPM
This commit
- add publish design tokens ga

feat: add publish design tokens ga

---

release-please/manifest.json

Because
- design tokens initial version is wrong
This commit
- fix design tokens initial version

fix(design-tokens): fix design tokens initial version

---

release-please/manifest.json

Because
- The version of design-tokens is wrong
- The release is not successfully
This commit
- re-release design tokens

chore(design-tokens): re-release design tokens

---

packages/design-tokens/README.md

Because
- We want to have full documentation about the design-tokens
This commit
- update docs about the theme switch

chore(docs): update docs about the theme switch

---

packages/design-tokens/src/buildTailwindPreset.ts

Because
- We should not replace all tailwind default styles
This commit
- extend style instead of replace them in design-tokens tailwind configuration

chore(design-tokens): extend style instead of replace them in design-tokens tailwind configuration

---

packages/design-tokens/tokens/global.json
packages/design-tokens/tokens/semantic/comp.json
packages/design-tokens/tokens/theme/dark.json
packages/design-tokens/tokens/theme/light.json

Because
- Spacing token was confusing and was conflicting with Tailwind naming convention
This commit
- Make spacing token align with Tailwind
- add disabled bg on semantic level

fix(design-tokens): fix spacing tokens to align with Tailwind convention

---

packages/design-tokens/README.md
packages/design-tokens/src/buildTailwindPreset.ts

Because
- In order to use Nextjs font optimization with TailwindCSS we need to use CSS variables
This commit
- use CSS variables to set up fontFamily

fix(design-tokens): use CSS variables to set up fontFamily

---

packages/design-tokens/src/buildCSSVariables.ts

Because
- boxShadow is not included in built package
This commit
- fix boxShadow is not included in built package

fix(design-tokens): fix boxShadow is not included in built package

---

.gitignore
package.json
packages/design-system/.storybook/preview.ts
packages/design-system/package.json
packages/design-system/tailwind.config.cjs
packages/design-tokens/package.json
turbo.json

Because
- design-token can't be successfully build into design-system storybook
This commit
- fix design-token can't be successfully build into design-system storybook

fix(design-system): fix design-token can't be successfully build into design-system storybook

---

packages/toolkit/src/components/cells/ConnectionTypeCell.tsx
packages/toolkit/src/lib/react-query-service/connector/source/useSourceWithPipelines.ts
packages/toolkit/src/lib/vdp-sdk/connector/types.ts
packages/toolkit/src/lib/vdp-sdk/pipeline/mocks.ts
packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
packages/toolkit/src/view/destination/CreateDestinationForm.tsx
packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SelectExistingDestinationFlow.tsx

Because
- the backend connector-definition format has been updated in order to support more connectors in future
This commit
- adopt new connector definition format

chore(toolkit): adopt new connector definition format

---

packages/design-tokens/src/buildCSSVariables.ts
packages/design-tokens/src/buildTailwindPreset.ts

Because
- We need disabled-within variant when implement the new input
This commit
- add disabled-within variant

feat(design-tokens): add disabled-within variant

---

packages/toolkit/src/lib/vdp-sdk/connector/types.ts

Because
- vendor and vendor_attributes are missing in connector definition
This commit
-  fix connector definition type

fix(toolkit): fix connector definition type

---

packages/design-system/src/new-ui/Dialog/Dialog.stories.tsx
packages/design-system/src/new-ui/Dialog/Dialog.tsx

Because
- Dialog.Close should not be inside the Dialog.Content
This commit
- remove Dialog.Close in the Dialog.Content

fix(design-system): remove Dialog.Close in the Dialog.Content

---

packages/toolkit/src/lib/react-query-service/pipeline/index.ts
packages/toolkit/src/lib/react-query-service/pipeline/useRenamePipeline.tsx
packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx

Because
- We need the ability to rename pipeline in pipeline-builder
This commit
- add rename pipeline mutation and react-query hook

feat(toolkit): add rename pipeline mutation and react-query hook

---

packages/toolkit/src/lib/airbytes/helpers/getConditionFormPath/getConditionFormPath.test.ts
packages/toolkit/src/lib/airbytes/helpers/getFieldsPaths/getFieldPaths.test.ts
packages/toolkit/src/lib/airbytes/helpers/pickSelectedConditionMap/pickSelectedConditionMap.test.ts
packages/toolkit/src/lib/airbytes/helpers/transformAirbyteSchemaToAirbyteFormTree/transformAirbyteSchemaToAirbyteFormTree.test.ts
packages/toolkit/src/lib/airbytes/helpers/transformAirbyteSchemaToAirbyteFormTree/transformAirbyteSchemaToAirbyteFormTree.ts
packages/toolkit/src/lib/airbytes/types.ts

Because
- Backend replace airbyte_secret with credential_field to make the definition more consistent
This commit
- replace airbyte_secret with credential_field

chore(toolkit): replace airbyte_secret with credential_field

---

packages/toolkit/src/components/cells/VisibilityCell.tsx

Because
- VisibilityCell wording is not correct
This commit
- fix VisibilityCell wording

fix(toolkit): fix VisibilityCell wording

---

packages/toolkit/src/view/ai/ConfigureAIForm.tsx

Because
- We should not allow user from changing the connector's name
This commit
- disable the user from changing the ai-connector

fix: disable the user from changing the ai-connector

---

packages/toolkit/src/view/ai/ConfigureAIForm.tsx
packages/toolkit/src/view/ai/CreateAIForm.tsx
packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx

Because
- There has typo in AI and blockchain forms
This commit
- fix type typo and export form schema in AI and blockchain forms

fix(toolkit): fix type typo and export form schema in AI and blockchain forms

---

packages/toolkit/src/lib/vdp-sdk/connector/types.ts

Because
- The Connector.configuration type is wrong
This commit
- fix Connector configuration type

fix: fix Connector configuration type

---

packages/toolkit/src/view/model/ModelTablePlaceholder.tsx
packages/toolkit/src/view/model/ModelsTable.tsx

Because
- model-hub link is not correct in ModelTabel
This commit
- fix model-hub link in ModelTabel

fix: fix model-hub link in ModelTabel

---

packages/toolkit/src/view/ai/ConfigureAIForm.tsx
packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx
packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx

Because
- After this release all the secret field will be input_only and its response will become "*****MASK*****"
- We fill in "" into airbyte secret fields when user focus it. 
- We fill in "" into AI, Blockchain form when user focus it and fill "*****MASK*****" when user blur the input if the connector had been created.
This commit
- adapt backend input_only secret design

feat(toolkit): adapt backend input_only secret design

---

packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx

Because
- Airbyte input only field wrongly access variable
This commit
- fix Airbyte input only field wrongly access variable

fix(toolkit): fix Airbyte input only field wrongly access variable

---

packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx

Because
- the access path of blockchain configuration has typo
This commit
- fix typo at ConfigureBlockchainForm

fix: fix typo at ConfigureBlockchainForm

---

packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx

Because
- form need to be consistent across the app
This commit
- make blockchain flow be consistent as other connector

fix: make blockchain flow be consistent as other connector

---

packages/design-system/src/new-ui/Toast/Toast.tsx
packages/design-system/src/new-ui/Toast/use-toast.tsx

Because
- toast at the bottom-right will block crucial action button
This commit
- move toast at the middle

feat: move toast at the middle

---

packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx

Because
- fix blockchain/create id field is wrongly disabled
This commit
- fix blockchain/create id field disabled issue

fix: fix blockchain/create id field disabled issue

---

packages/design-system/src/new-ui/Skeleton/Skeleton.tsx
packages/design-system/src/new-ui/Skeleton/Skelton.stories.tsx
packages/design-system/src/new-ui/Skeleton/index.ts
packages/design-system/src/new-ui/index.ts

Because
- we need skeleton to indicator loading state
This commit
- add skeleton

feat: add skeleton

---

packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx

Because
- We need a loading state for draggable item
This commit
-  add DraggableItem skeleton

feat: add DraggableItem skeleton

---

packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx

Because
- pipeline-builder unselect not working
This commit
- fix pipeline-builder unselect not working

fix: fix pipeline-builder unselect not working

---

packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx

Because
- pipeline builder ondelete has issue when the form is dirty
This commit
-  fix pipeline builder ondelete issue

fix(toolkit): fix pipeline builder ondelete issue

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx

Because
- pipeline-builder's node name is overflow
This commit
- fix pipeline-builder's node name overflow text issue

fix(pipeline-builder): fix pipeline-builder's node name overflow text issue

---

packages/toolkit/package.json
packages/toolkit/src/view/ai/ConfigureAIForm.tsx
packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx

Because
- deactivate empty path icon looks like checkbox
This commit
- replace empty icon with fill icon in activate/deactivate button

fix: replace empty icon with fill icon in activate/deactivate button

---

packages/toolkit/src/lib/pipeline-builder/createInitialGraphData.tsx
packages/toolkit/src/lib/store/usePipelineBuilderStore.ts
packages/toolkit/src/lib/type/pipeline-builder.ts
packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx

Because
- we need to provide richer visual hint
This commit
- map edge animated status with the state of pipeline

feat: map edge animated status with the state of pipeline

---

packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx

Because
- save pipeline action not correctly early return
This commit
- fix save pipeline action not correctly early return

fix: fix save pipeline action not correctly early return

---

packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx

Because
- spin animation text color is wrong
This commit
- fix the spin animation text color of save button in pipeline-builder

fix: fix the spin animation text color of save button in pipeline-builder

---

packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx

Because
- connector form in pipeline-builder wrongly disable connect button issue
This commit
- fix connector form in pipeline-builder wrongly disable connect button issue

fix: fix connector form in pipeline-builder wrongly disable connect button issue

---

packages/design-system/src/new-ui/Button/Button.stories.tsx
packages/design-system/src/new-ui/LinkButton/LinkButton.stories.tsx
packages/design-system/src/new-ui/TagButton/TagButton.stories.tsx

Because
- we need to example for asChild in components in stories
This commit
- example for asChild in components

feat: example for asChild in components

---

packages/toolkit/src/view/dashboard/FilterByDay.tsx
packages/toolkit/src/view/destination/CreateDestinationForm.tsx
packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx

Because
- If div has onClick handler it should also listen to keyboard
This commit
- fix div non interactive lint issue

fix: fix div non interactive lint issue

---

packages/design-system/src/new-ui/Icons/ArrowNarrowLeft.tsx
packages/design-system/src/new-ui/Icons/ArrowNarrowRight.tsx
packages/design-system/src/new-ui/Icons/index.ts

Because
- we new `<Icons.ArrowNarrowLeft />` and `<Icons.ArrowNarrowRight />` icon
This commit
- `<Icons.ArrowNarrowLeft />` and `<Icons.ArrowNarrowRight />` icon

feat: ArrowNarrowLeft and ArrowNarrowRight

---

packages/toolkit/src/lib/pipeline-builder/getConnectorPresets.ts

Because
- Open AI preset is supported
This commit
- add OpenAI preset

feat(toolkit): add OpenAI preset

---

packages/design-system/src/new-ui/Button/Button.stories.tsx

Because
- we need `!rounded-none` example button
This commit
- `!rounded-none` example button

feat: rounded-none example button

---

packages/design-system/src/new-ui/Icons/ChevronSelectorVertical.tsx
packages/design-system/src/new-ui/Icons/index.ts

Because
- we need `<ChevronSelectorVertical />` icon
This commit
- `<ChevronSelectorVertical />` icon

feat: ChevronSelectorVertical icon

---

packages/design-system/src/new-ui/Checkbox/Checkbox.stories.tsx
packages/design-system/src/new-ui/Checkbox/Checkbox.tsx

Because
- The style of the checkbox didn't align with the design-doc
This commit
- fix the style of the checkbox

fix(design-system): fix the style of checkbox

---

packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx

Because
- pipeline-builder CustomNode not stay on top issue, causing user can't link nodes
This commit
- fix pipeline-builder CustomNode not stay on top issue

fix(toolkit): fix pipeline-builder CustomNode not stay on top issue

---

packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx

Because
- create blockchain wrong label
This commit
- create blockchain wrong label

fix: create blockchain wrong label

---

packages/toolkit/src/lib/dashboard/index.ts
packages/toolkit/src/lib/dashboard/sortByTriggerTime.ts

Because
- add sortByTriggerTime for pipeline triggertable
This commit
- add sortByTriggerTime for pipeline triggertable

chore(toolkit): add sortByTriggerTime for pipeline triggertable

---

packages/toolkit/src/view/pipeline-builder/FlowControl.tsx

Because
- trigger pipeline snippet has typo
This commit
- fix snippet typo

fix: fix snippet typo

---

packages/toolkit/src/view/blockchain/BlockchainForm.tsx

Because
- Blockchain validation has some issue on license
This commit
- fix Blockchainform validation

fix: fix Blockchainform validation

---

packages/toolkit/src/view/model/ModelHubCreatePageMainView.tsx

Because
- fix model-hub view didn't expose disabledCreateModel prop
This commit
- fix model-hub view didn't expose disabledCreateModel prop

fix(toolkit): fix model-hub view didn't expose disabledCreateModel prop

---

packages/toolkit/src/view/model/CreateModelForm.tsx

Because
- Backend had supported name space
This commit
- fix model name not included user name when create model

fix: fix model name not included user name when create model

---

packages/toolkit/package.json
packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts

Because
- We don't need accessToken in this action
This commit
- remove the accessToken props in the authLoginAction

fix(sdk): remove the accessToken props in the authLoginAction

---

packages/toolkit/package.json
packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts

Because
- we need this endpoint to validate token
This commit
- add validate token endpoint sdk

feat(toolkit): add validate token endpoint sdk

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx

Because
- When the pipeline is new we should not query its pipelineRelease
This commit
- fix pipeline-builder wrongly request backend for pipelineReleases

fix(toolkit): fix pipeline-builder wrongly request backend for pipelineReleases

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx

Because
- For better UX
This commit
- when user delete the full pipeline name and blur out we recover the form with previous name

feat(toolkit): when user delete the full pipeline name and blur out we recover the form with previous name

---

packages/design-system/src/new-ui/Command/Command.tsx

Because
- We need additional props to control command
This commit
- expose additional classname in CommandDialog

chore(design-system): expose additional classname in CommandDialog

---

packages/design-system/src/new-ui/Dialog/Dialog.tsx

Because
- improve DX
This commit
- expose the classname of Dialog.Close

fix(design-system): expose the classname of Dialog.Close

---

packages/design-system/src/new-ui/Tabs/Tabs.tsx

Because
- To make the implementation clear
This commit
- remove the initial style of Tabs

chore: remove the initial style of Tabs

---

packages/toolkit/src/view/pipeline/PipelinesTable.tsx
packages/toolkit/src/view/resource/ResourcesTable.tsx

Because
- delete resource dialog is too wide
This commit
- fix delete resource dialog is too wide

fix(toolkit): fix delete resource dialog is too wide

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx

Because
- editing pipeline name when pipeline is new will cause unexpected behavior
This commit
- fix editing pipeline name when pipeline is new will cause unexpected behavior

fix(toolkit): fix editing pipeline name when pipeline is new will cause unexpected behavior

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx

Because
- Empower user to share
This commit
- user can view shared pipeline's versions

feat(toolkit): user can view shared pipeline's versions

---

packages/toolkit/package.json
packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx

Because
- to better improve flexiblity
This commit
- expose namespace on modelHubDetailsPage

feat(toolkit): expose namespace on modelHubDetailsPage

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx

Because
- Improve UX
This commit
- User can identify the node's name editor and pipeline name's editor when focus on the input

feat: user can identify the node's name editor and pipeline name's editor when focus on the input

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
packages/toolkit/src/view/pipeline-builder/components/StartNode.tsx

Because
- improve UX
This commit
- user wont get confused by handler if there has no edge on it

feat(pipeline-builder): user wont get confused by handler if there has no edge on it

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx

Because
- can not filter their existing resource when create resource directly on pipeline builder
This commit
- fix user can not filter their existing resource when create resource directly on pipeline builder

fix: fix user can not filter their existing resource when create resource directly on pipeline builder

---

packages/toolkit/src/view/ai/AIForm.tsx

Because
- component configuration field description for instill model is wrong
This commit
- fix the wrong component configuration field description for instill model

fix(toolkit): fix the wrong component configuration field description for instill model

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/components/connector-node/ResourceNameTag.tsx

Because
- improve UX
This commit
- User can better differentiate the resource_name on right panel and the node_name on the node

feat(pipeline-builder): User can better differentiate the resource_name on right panel and the node_name on the node

---

packages/toolkit/package.json
packages/toolkit/src/view/data/DataComponentForm.tsx
packages/toolkit/src/view/pipeline-builder/RightPanel.tsx
packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/components/connector-node/InputPropertyItem.tsx
packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts
packages/toolkit/src/view/pipeline-builder/lib/getPropertiesFromOpenAPISchema.ts
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ArrayObjectField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/FieldRoot.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useConnectorTestModeOutputFields.tsx

Because
- improve UX
This commit
- user can better identify some nested output on connector nodes

feat(toolkit): user can better identify some nested output on connector nodes

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx
packages/toolkit/src/view/pipeline-builder/use-node-input-fields/NumberField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-input-fields/NumbersField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-input-fields/useStartOperatorTestModeInputForm.tsx

Because
- when trigger pipeline, we wrongly parsed string value to number
This commit
- fix a bug when trigger pipeline, we wrongly parsed string value to number

fix(toolkit): fix a bug when trigger pipeline, we wrongly parsed string value to number

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/NumberField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/NumbersField.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx

Because
- when create fields on the end operator will wrongly use the key from the previous edited field
This commit
- Fix a bug when create fields on the end operator will wrongly use the key from the previous edited field

fix(pipeline-builder): fix a bug when create fields on the end operator will wrongly use the key from the previous edited field

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
packages/toolkit/src/view/pipeline-builder/lib/createGraphLayout.tsx
packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useConnectorTestModeOutputFields.tsx

Because
- improve UX
This commit
- user can have consistent node width between TEST_VIEW and BUILD_VIEW

feat(pipeline-builder): user can have consistent node width between TEST_VIEW and BUILD_VIEW

---

packages/toolkit/package.json
packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx

Because
- data connector can't have multiple free-form fields
This commit
- fix data connector can't have multiple free-form fields

fix(pipeline-builder): fix data connector can't have multiple free-form fields
