- package.json
- src/components/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- src/components/TextAreas/BasicTextArea/BasicTextArea.stories.tsx
- src/components/TextAreas/TextAreaBase/TextAreaBase.tsx
- src/components/TextFields/TextFieldBase/TextFieldBase.tsx
- src/components/UploadFileFields/BasicUploadFileField/BasicUploadFileField.stories.tsx
- src/components/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
- src/hooks/useWindowSize.tsx
- src/utils/index.ts
- tsconfig.json
- yarn.lock
Because
- We need typescript strict rule to ensure the correctness of design-system
This commit
-  enforce typescript strict rule
> feat: enforce typescript strict rule

- package.json
- src/components/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
Because
- File upload field non re-render when delete the input value
This commit
- fix above issue
> fix: fix upload file not re render

- package.json
- src/components/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Single select can't set default value
This commit
- Fix the missing value prop
> fix: fix single select value issue

- package.json
- src/components/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
Because
- Upload file input field's id attribute is wrong
This commit
> fix: fix upload file input issue

- README.md
- package.json
- src/components/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- src/components/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Single select's onChangeInput type is wrong
This commit
> fix: fix single select's onChangeInput type

- package.json
- src/components/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Single select's icon size is wrong
This commit
> fix: fix single select icon size

- package.json
- src/components/InputDescriptions/BasicInputDescription/BasicInputDescription.tsx
- src/components/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.stories.tsx
- src/components/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.tsx
- src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.stories.tsx
- src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx
Because
- We need a way for user to close the message box
This commit
- Make progress message box closable
> feat: make progress message box closable

- package.json
- src/components/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx
Because
- Message box bg color is wrong
This commit
> fix: fix message box color

- src/components/Icons/ArrowIcons/RotatableArrowIcon/RotatableArrowIcon.stories.tsx
- src/components/Icons/ArrowIcons/RotatableArrowIcon/RotatableArrowIcon.tsx
- src/components/Icons/ArrowIcons/RotatableArrowIcon/index.ts
- src/components/Icons/ArrowIcons/index.ts
- src/components/Icons/index.ts
Because
- We need rotatable arrow icon
This commit
- add RotatableArrowIcon
> feat: add RotatableArrowIcon

- package.json
- src/components/Icons/index.ts
Because
- Icon export is wrong
This commit
> fix: fix icons export

- .eslintrc.js
- package.json
- src/generators/components/PixelBaseBlock/PixelBaseBlock.stories.tsx
- src/generators/components/PixelBaseBlock/PixelBaseBlock.tsx
- src/generators/components/PixelBaseBlock/index.ts
- src/generators/components/PixelDiagramGenerator/PixelDiagramGenerator.stories.tsx
- src/generators/components/PixelDiagramGenerator/PixelDiagramGenerator.tsx
- src/generators/components/PixelDiagramGenerator/index.ts
- src/generators/components/SolidDiagramGenerator/BackSlashBlock.tsx
- src/generators/components/SolidDiagramGenerator/BlankBlock.tsx
- src/generators/components/SolidDiagramGenerator/HorizontalRectBlock.tsx
- src/generators/components/SolidDiagramGenerator/SlashBlock.tsx
- src/generators/components/SolidDiagramGenerator/SolidDiagramGenerator.stories.tsx
- src/generators/components/SolidDiagramGenerator/SolidDiagramGenerator.tsx
- src/generators/components/SolidDiagramGenerator/VerticalRectBlock.tsx
- src/generators/components/SolidDiagramGenerator/index.ts
- src/generators/index.ts
- src/generators/types/generator.ts
- src/generators/utils/common.ts
- src/generators/utils/pixel.ts
- src/generators/utils/solid.ts
- src/index.ts
Because
- Move generators related code from product-website to design-system
This commit
- Add generator related components
> feat: add generators

- package.json
- src/ui/Buttons/ButtonBase/ButtonBase.stories.tsx
- src/ui/Buttons/ButtonBase/ButtonBase.tsx
- src/ui/Buttons/ButtonBase/index.ts
- src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.stories.tsx
- src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx
- src/ui/Buttons/CollapseSidebarButton/index.ts
- src/ui/Buttons/OutlineButton/OutlineButton.stories.tsx
- src/ui/Buttons/OutlineButton/OutlineButton.tsx
- src/ui/Buttons/OutlineButton/index.ts
- src/ui/Buttons/SolidButton/SolidButton.stories.tsx
- src/ui/Buttons/SolidButton/SolidButton.tsx
- src/ui/Buttons/SolidButton/index.ts
- src/ui/Buttons/index.ts
- src/ui/Logo/Logo.stories.tsx
- tailwind.config.js
Because
- To manage button in design-system
This commit
- Add ButtonBase, SolidButton, OutlineButton and CollapseSidebarButton
> feat: Add Button components

- package.json
- src/ui/Buttons/ButtonBase/ButtonBase.tsx
- src/ui/Buttons/OutlineButton/OutlineButton.stories.tsx
- src/ui/Buttons/OutlineButton/OutlineButton.tsx
- src/ui/Buttons/SolidButton/SolidButton.stories.tsx
- src/ui/Buttons/SolidButton/SolidButton.tsx
- src/ui/Buttons/TextButton/TextButton.stories.tsx
- src/ui/Buttons/TextButton/TextButton.tsx
- src/ui/Buttons/TextButton/index.ts
- src/ui/Buttons/index.ts
Because
- We need TextButton
This commit
- Add TextButton
- Refactor button prop - variant to color
- Fix typo
> feat: add text button

- package.json
- src/index.ts
- src/types/general.ts
- src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
- src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
- src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
- src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
Because
- We want to provide more information for form builder
This commit
- Support input event prop
> feat: add event prop into Input components' onChangeInput function

- src/ui/Icons/CrossIcon/CrossIcon.stories.tsx
- src/ui/Icons/CrossIcon/CrossIcon.tsx
- src/ui/Icons/CrossIcon/index.ts
- src/ui/Icons/LinkedInIcon/LinkedInIcon.stories.tsx
- src/ui/Icons/LinkedInIcon/LinkedInIcon.tsx
- src/ui/Icons/LinkedInIcon/index.ts
- src/ui/Icons/PinIcon/PinIcon.stories.tsx
- src/ui/Icons/PinIcon/PinIcon.tsx
- src/ui/Icons/PinIcon/index.ts
- src/ui/Icons/ToolboxIcon/ToolboxIcon.stories.tsx
- src/ui/Icons/ToolboxIcon/ToolboxIcon.tsx
- src/ui/Icons/ToolboxIcon/index.ts
- src/ui/Icons/TwitterIcon/TwitterIcon.stories.tsx
- src/ui/Icons/TwitterIcon/TwitterIcon.tsx
- src/ui/Icons/TwitterIcon/index.ts
- src/ui/Icons/index.ts
Because
- We need more icons
This commit
- Add CrossIcon, LinkedInIcon, PinIcon, TwitterIcon, ToolBoxIcon
> feat: add more icons

- package.json
- src/ui/Logo/VdpLogo.stories.tsx
- src/ui/Logo/VdpLogo.tsx
- src/ui/Logo/index.ts
Because
- We have new VDP icon 
This commit
- Add vdp icon
> feat: add vdp icon

- package.json
- src/ui/Logo/VdpLogo.stories.tsx
- src/ui/Logo/VdpLogo.tsx
Because
- VDP logo is not correctly displayed
This commit
- Fix VDP logo
> fix: fix vdp logo

- package.json
- src/ui/Icons/MinusIcon/MinusIcon.stories.tsx
- src/ui/Icons/MinusIcon/MinusIcon.tsx
- src/ui/Icons/MinusIcon/index.ts
- src/ui/Icons/PlusIcon/PlusIcon.stories.tsx
- src/ui/Icons/PlusIcon/PlusIcon.tsx
- src/ui/Icons/PlusIcon/index.ts
- src/ui/Icons/index.ts
Because
- We have new icons
This commit
- Add plus and minus icon
> feat: add plus and minus icon

- package.json
- src/ui/Icons/GitHubIcon/GitHubIcon.stories.tsx
- src/ui/Icons/IconBase/IconBase.tsx
Because
- IconBase wrongly throw an error
This commit
- Fix IconBase wrongly throw an error issue
> fix: fix IconBase wrongly throw an error issue

- package.json
- src/ui/Icons/AsyncArrowsIcon/AsyncArrowsIcon.stories.tsx
- src/ui/Icons/AsyncArrowsIcon/AsyncArrowsIcon.tsx
- src/ui/Icons/AsyncArrowsIcon/index.ts
- src/ui/Icons/SyncArrowsIcon/SyncArrowsIcon.stories.tsx
- src/ui/Icons/SyncArrowsIcon/SyncArrowsIcon.tsx
- src/ui/Icons/SyncArrowsIcon/index.ts
- src/ui/Icons/index.ts
This commit adds sync and async arrow icons.
> feat: add async and sync arrow icon

- package.json
- src/ui/Accordion/AccordionBase/AccordionBase.tsx
- src/ui/Accordion/BasicAccordion/BasicAccordion.tsx
- src/ui/Accordion/BgIconAccordion/BgIconAccordion.tsx
This commit adds width and headerIconColor prop into the accordion to extend this component's flexibility.
> feat: add width and headerIconColor prop into the accordion

- package.json
- src/ui/Accordion/AccordionBase/AccordionBase.stories.tsx
- src/ui/Accordion/AccordionBase/AccordionBase.tsx
- src/ui/Accordion/BasicAccordion/BasicAccordion.stories.tsx
- src/ui/Accordion/BasicAccordion/BasicAccordion.tsx
- src/ui/Accordion/BgIconAccordion/BgIconAccordion.stories.tsx
- src/ui/Accordion/BgIconAccordion/BgIconAccordion.tsx
- src/ui/Buttons/ButtonBase/ButtonBase.tsx
- src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx
- src/ui/Buttons/OutlineButton/OutlineButton.tsx
- src/ui/Buttons/SolidButton/SolidButton.tsx
- src/ui/Buttons/TextButton/TextButton.tsx
- src/ui/Icons/MenuIcon/MenuIcon.stories.tsx
- src/ui/Icons/MenuIcon/MenuIcon.tsx
- src/ui/Icons/MenuIcon/index.ts
- src/ui/Icons/index.ts
- src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- tailwind.config.js
This commit implements several changes
- add shadow and hoveredShadow prop into Buttons
- add white variant into SolidButton
- allow multiple items at Accordion
- add primaryLight variant into OutlineButton
- refactor how SingleSelectBase get element position
> feat: release 0.0.129

- package.json
- src/ui/Icons/FilterIcon/FilterIcon.stories.tsx
- src/ui/Icons/FilterIcon/FilterIcon.tsx
- src/ui/Icons/FilterIcon/index.ts
- src/ui/Icons/index.ts
This PR adds FilterIcon and bump version to 0.0.131
> feat: Add filter icon

- package.json
Because
- version should be 0.0.137
This commit
- Fix design-system version
> fix: fix design-system version

- package.json
- src/index.ts
- src/toolkits/getModelInstanceTaskToolkit.tsx
- src/toolkits/index.ts
- src/types/general.ts
- src/ui/Accordion/AccordionBase/AccordionBase.stories.tsx
- src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Unify tool from instill.tech, console and console-cloud into design-system
This commit
- add getModelInstanceTaskToolkit toolkit
> feat: add getModelInstanceTaskToolkit toolkit

- package.json
- src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Single Select style is wrong when in inset label type
This commit
-  fix single select inset label
> fix: fix single select inset label

- .changeset/nervous-nails-boil.md
- .changeset/nine-games-unite.md
- .changeset/two-games-run.md
- .changeset/violet-tables-rule.md
- packages/eslint-config-cortex/package.json
- packages/ui/package.json
- packages/ui/src/ui/InputDescriptions/BasicInputDescription/BasicInputDescription.stories.tsx
- packages/ui/src/ui/InputDescriptions/BasicInputDescription/BasicInputDescription.tsx
- packages/ui/src/ui/InputDescriptions/InputDescriptionBase/InputDescriptionBase.stories.tsx
- packages/ui/src/ui/InputDescriptions/InputDescriptionBase/InputDescriptionBase.tsx
- packages/ui/src/ui/InputDescriptions/InputDescriptionBase/index.ts
- packages/ui/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- packages/ui/src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
- packages/ui/src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
- packages/ui/src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
- packages/ui/src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
Because
- Build failed
This commit
- fix build issue and re-release package
> fix: fix build issue and re-release

- .changeset/silly-goats-shave.md
- packages/ui/tsconfig.json
- tsconfig.base.json
Because
- we want to reuse tsconfig
This commit
-  add base tsconfig at the root
> feat: add base tsconfig

- .changeset/cold-dogs-cover.md
- .changeset/serious-gorillas-share.md
- packages/toolkit/package.json
- packages/toolkit/src/dot/README.md
- packages/toolkit/src/dot/index.test.ts
- packages/toolkit/src/dot/index.ts
- packages/toolkit/src/index.ts
- packages/ui/.eslintrc.js
- packages/ui/package.json
- pnpm-lock.yaml
Because
- add dot lib into toolkit
This commit
- add dot lib into toolkit
> feat: add dot lib

- .changeset/old-poems-give.md
- packages/toolkit/esbuild.js
- packages/toolkit/src/sdk/index.ts
- packages/toolkit/src/utility/getHumanReadableStringFromTime/getHumanReadableStringFromTime.test.ts
- packages/toolkit/src/utility/getHumanReadableStringFromTime/getHumanReadableStringFromTime.ts
- packages/toolkit/src/utility/getHumanReadableStringFromTime/index.ts
- packages/toolkit/src/utility/groupBy.ts
- packages/toolkit/src/utility/handle.ts
- packages/toolkit/src/utility/index.ts
Because
- centralize the function we have across open-source and cloud app
This commit
- add multiple utilities
> feat: add multiple utilities

- release-please/config.json
Because
- the config is wrong
This commit
- fix google release please manifest config
> feat: fix google release please manifest config

- release-please/manifest.json
Because
- we need to specific initial version
This commit
- update packages version
> chore: update release version

- .github/workflows/release.yml
- packages/eslint-config-cortex/package.json
- packages/toolkit/package.json
- packages/ui/package.json
- release-please/manifest.json
Because
- the release action is wrong
This commit
- rollback version and update release action
> chore: rollback version and update release action

- .github/workflows/release.yml
- package.json
- packages/eslint-config-cortex/package.json
- packages/toolkit/package.json
- packages/ui/package.json
- release-please/manifest.json
Because
- The build and publish step have bugs
This commit
- fix build and publish steps
> fix: fix build and publish steps

- .github/workflows/release.yml
- packages/eslint-config-cortex/package.json
- packages/toolkit/package.json
- packages/ui/package.json
- release-please/manifest.json
Because
- action's npm token has wrong reference
This commit
- update action and version
> feat: update action and version

- README.md
- packages/toolkit/package.json
- packages/toolkit/src/store/README.md
- packages/toolkit/src/store/index.ts
- packages/toolkit/src/store/useConfigureModelFormStore.ts
- packages/toolkit/src/store/useConfigureProfileFormStore.tsx
- packages/toolkit/src/store/useModalStore.ts
- packages/toolkit/src/store/useResourceFormStore.ts
- packages/toolkit/tsconfig.json
- pnpm-lock.yaml
Because
- We want to centralize the components and functions into cortex
This commit
- add toolkit into cortext
> feat: add stores

- packages/toolkit/src/utility/config.ts
- packages/ui/src/ui/FormRoot.tsx
- packages/ui/src/ui/index.ts
Because
This commit
- add FormRoot to ui
> feat: add FormRoot

- packages/ui/src/ui/FormRoot.tsx
- packages/view/package.json
- packages/view/src/index.ts
- packages/view/src/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
- packages/view/src/mgmt/ConfigureProfileForm/ConfigureProfileForm.tsx
- packages/view/src/mgmt/ConfigureProfileForm/FirstNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/LastNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/NewsletterSubscriptionField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/OrgNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/RoleField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/UserNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/index.ts
- packages/view/src/mgmt/index.ts
- pnpm-lock.yaml
Because
- centralize re-usable components
This commit
- add ConfigureProfileForm into view
> feat: add ConfigureProfileForm into view

- packages/toolkit/package.json
- packages/toolkit/src/amplitude.ts
- packages/toolkit/src/context/AmplitudeContext.ts
- packages/toolkit/src/context/index.ts
- packages/toolkit/src/index.ts
- pnpm-lock.yaml
Because
- centralize functions and components
This commit
- add amplitude context and helper into toolkit
> feat: add amplitude context and helper into toolkit

- packages/toolkit/README.md
- packages/toolkit/package.json
- packages/toolkit/src/hook/index.ts
- packages/toolkit/src/hook/useCreateUpdateDeleteResourceGuard.tsx
- packages/toolkit/src/hook/useRefSize.ts
- packages/toolkit/src/hook/useSearchedResources.tsx
- packages/toolkit/src/hook/useStateOverviewCounts.ts
- packages/toolkit/src/hook/useWarnUnsavedChanges.tsx
- packages/toolkit/src/hook/useWindowSize.ts
- pnpm-lock.yaml
Because
- centralize hooks into `toolkit`
This commit
- add necessary hooks
> feat: add hooks

- packages/toolkit/src/store/index.ts
- packages/toolkit/src/store/useConfigureModelFormStore.ts
- packages/toolkit/src/store/useModalStore.ts
- packages/toolkit/src/store/useResourceFormStore.ts
Because
- ConfigureModelFormStore, ModalStore, CreateResourceFormStore didn't have correct export type
This commit
-  export store type and update export path
> feat: export store type and update export path

- packages/design-system/src/ui/ModalRoot.tsx
- packages/design-system/src/ui/index.ts
Because
This commit
- add ModalRoot into design-system
> feat: add ModalRoot into design-system

- packages/view/src/DeleteResourceModal.tsx
- packages/view/src/index.ts
Because
This commit
- add DeleteResourceModal
> feat: add DeleteResourceModal

- packages/toolkit/src/store/useConfigureModelFormStore.ts
- packages/toolkit/src/store/useConfigurePipelineFormStore.ts
- packages/toolkit/src/store/useConfigureProfileFormStore.tsx
- packages/toolkit/src/store/useMessageBoxStore.tsx
- packages/toolkit/src/store/useModalStore.ts
Because
- centralize stores
This commit
- add useConfigureModelFormStore
> feat: add useConfigureModelFormStore

- packages/design-system/src/ui/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx
- packages/toolkit/src/store/index.ts
- packages/toolkit/src/store/useConfigurePipelineFormStore.ts
- packages/toolkit/src/store/useConfigureProfileFormStore.tsx
- packages/toolkit/src/store/useCreateSourceFormStore.ts
- packages/view/src/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
- packages/view/src/mgmt/ConfigureProfileForm/FirstNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/LastNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/NewsletterSubscriptionField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/OrgNameField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/RoleField.tsx
- packages/view/src/mgmt/ConfigureProfileForm/UserNameField.tsx
Because
- centralize stores
This commit
- add create source form store
> feat: add create source form store

- packages/toolkit/package.json
Because
- the published folder is wrong
This commit
- fix the published folder
> fix: fix packagejson files prop

- packages/design-system/esbuild.js
- packages/design-system/package.json
- packages/toolkit/esbuild.js
- packages/toolkit/package.json
Because
- we want to export ESM module only
This commit
- only export ESM module
> feat: only export ESM module

- packages/toolkit/src/view/index.ts
- packages/toolkit/src/view/model/ChangeModelInstanceStateToggle.tsx
- packages/toolkit/src/view/model/index.ts
- packages/toolkit/src/view/pipeline/ChangePipelineStateToggle.tsx
- packages/toolkit/src/view/pipeline/index.ts
Because
- centralize component
This commit
- add change pipeline & modelInstance toggle state button
> feat: [INS-232] add change pipeline & modelInstance toggle state button

- packages/toolkit/src/lib/amplitude/helper.ts
- packages/toolkit/src/lib/amplitude/index.ts
- packages/toolkit/src/lib/amplitude/type.ts
- packages/toolkit/src/lib/amplitude/useSendAmplitudeData.ts
Because
- centralize helper functions
This commit
- add useSendAmplitudeData into cortex
> feat: [ins-233] add useSendAmplitudeData into cortex

- packages/design-system/.eslintrc.cjs
- packages/design-system/esbuild.js
- packages/design-system/package.json
- packages/toolkit/.eslintrc.cjs
- packages/toolkit/esbuild.js
- packages/toolkit/package.json
- packages/toolkit/src/lib/vdp-sdk/connector/destination/queries.ts
- packages/toolkit/src/lib/vdp-sdk/connector/source/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/connector/source/queries.ts
- packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts
- packages/toolkit/src/lib/vdp-sdk/model/actions.ts
- packages/toolkit/src/lib/vdp-sdk/model/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/model/queries.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
Because
- we miss type declaration in package.json
This commit
- fix packagejson type declaration
> fix: fix packagejson type declaration

- packages/toolkit/package.json
- packages/toolkit/src/lib/utility/config.ts
- packages/toolkit/src/lib/utility/cookie.ts
- packages/toolkit/src/lib/utility/determineModelState.ts
- packages/toolkit/src/lib/utility/getHumanReadableStringFromTime/getHumanReadableStringFromTime.ts
- packages/toolkit/src/lib/utility/groupBy.ts
- packages/toolkit/src/lib/utility/handle.ts
- packages/toolkit/src/lib/utility/index.ts
- packages/toolkit/src/lib/utility/validateResourceId/validateResourceId.ts
- pnpm-lock.yaml
- turbo.json
Because
- centralize helper function
This commit
- add cookie utility into toolkit
> feat: add cookie utility into toolkit

- apps/cortex-playground/package.json
- apps/cortex-playground/tailwind.config.js
- packages/design-system/package.json
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- packages/toolkit/src/view/airbyte/OneOfConditionSection.tsx
- packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
Because
- SingleSelectBase has wrong prop name
This commit
- fix SingleSelectBase wrong prop name issue
> fix: fix SingleSelectBase wrong prop name issue

- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/index.ts
- pnpm-lock.yaml
Because
- experiment export path
This commit
- experiment export path of BasicSingleSelect
> fix: experiment export path

- packages/design-system/.eslintignore
- packages/design-system/esbuild.js
- packages/design-system/package.json
- pnpm-lock.yaml
Because
-  test esbuild
This commit
- test esbuild
> fix: test esbuild

- packages/design-system/package.json
- packages/design-system/tsup.config.ts
- packages/toolkit/package.json
- packages/toolkit/tsup.config.ts
Because
- export cjs file to fix some import bug
This commit
- export cjs file
> fix: export cjs file

- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- the single select style focus style is in correct
This commit
- fix single select focus style and export more props
> fix: fix single select focus style and export more props

- apps/cortex-playground/package.json
- apps/cortex-playground/src/pages/_app.tsx
- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/view/index.ts
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
- packages/toolkit/src/view/source/CreateSourceForm/SourceDefinitionField.tsx
- packages/toolkit/src/view/source/CreateSourceForm/index.ts
- packages/toolkit/src/view/source/index.ts
- pnpm-lock.yaml
Because
This commit
- add create source form
> feat: add create source form

- packages/toolkit/src/lib/store/useCreateResourceFormStore.ts
- packages/toolkit/src/view/FormVerticalDivider.tsx
- packages/toolkit/src/view/HorizontalDivider.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineProgress/CreatePipelineProgress.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineProgress/ProgressStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineProgress/index.ts
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/UseExistingDestinationFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/index.ts
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/UseExistingModelInstanceFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/index.ts
- packages/toolkit/src/view/pipeline/CreatePipelineForm/index.ts
Because
This commit
- add CreatePipelineForm into toolkit
> feat: add CreatePipelineForm into toolkit

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/destination/index.ts
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelWithPresetForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/DeployModelInstanceCard.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceForm.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
Because
This commit
- Refactor ConfigureDestinationForm and add it into `toolkit`
> feat: [INS-278] Refactor ConfigureDestinationForm and add it into `toolkit`

- apps/cortex-playground/src/pages/_app.tsx
- apps/cortex-playground/src/pages/index.tsx
- packages/design-system/package.json
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SelectItem.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Select's icon didn't get displayed correctly
This commit
- fix select icon issue
> fix: [INS-276] fix select icon issue

- apps/cortex-playground/src/pages/index.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- Select is not correctly disabled
This commit
- fix select not disabled
> fix: [INS-277] fix select not disabled

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/lib/react-query-service/pipeline/usePipeline.ts
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelConfirmationModal.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelWithPresetForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/DeployModelInstanceCard.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/UseExistingDestinationFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/UseExistingModelInstanceFlow.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceForm.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
Because
- The props are missing in the form
This commit
- fix missing props in the form
> fix: fix missing props in the form

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/lib/store/useConfigureModelFormStore.ts
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/model/ConfigureModelForm.tsx
- packages/toolkit/src/view/model/index.ts
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
Because
This commit
- add ConfigureModelForm into toolkit
> feat: [INS-297] add ConfigureModelForm into toolkit

- packages/toolkit/src/view/PaginationListContainer.tsx
- packages/toolkit/src/view/index.ts
Because
This commit
- add PaginationListContainer
> feat: add PaginationListContainer

- packages/design-system/package.json
- packages/toolkit/package.json
Because
- test around package.json export
This commit
- update how we handle export
> feat: update how we handle export

- packages/toolkit/src/view/model/ConfigureModelInstanceForm.tsx
- packages/toolkit/src/view/model/index.ts
Because
-  centralize components
This commit
- add ConfigureModelInstanceForm into toolkit
> feat: [INS-312] add ConfigureModelInstanceForm into toolkit

- .github/workflows/test.yml
- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
- packages/toolkit/src/view/source/index.ts
Because
This commit
- add sources table into toolkit
> feat: [INS-315] add sources table into toolkit

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/model/index.ts
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
This commit
- add ModelsTable into toolkit
> feat: add ModelsTable into toolkit

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/components/cells/ConnectionTypeCell.tsx
- packages/toolkit/src/components/cells/ModeCell.tsx
- packages/toolkit/src/components/cells/ModelDefinitionCell.tsx
- packages/toolkit/src/components/cells/ModelInstancesCell.tsx
- packages/toolkit/src/components/cells/ModelsCell.tsx
- packages/toolkit/src/components/cells/NameCell.tsx
- packages/toolkit/src/components/cells/PipelinesCell.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/pipeline/index.ts
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
This commit
- add pipeline table into toolkit
> feat: add pipeline table into toolkit

- packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts
Because
- user related endpoint protobuf had been updated
This commit
- fix user related request
> fix: fix user related request

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileForm.tsx
Because
- configure profile padding is wrong
This commit
- fix configure profile form padding
> fix: fix configure profile form padding

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileForm.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/FirstNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/LastNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/NewsletterSubscriptionField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/OrgNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/UserNameField.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/PipelineDescriptionField.tsx
Because
- Configure Profile Form has wrong functionality
This commit
- fix configure profile form
> fix: fix configure profile form

- apps/cortex-playground/src/pages/index.tsx
- packages/toolkit/src/lib/store/useCreateResourceFormStore.ts
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/index.ts
Because
This commit
- add normal create model form
> feat: [INS-400] add normal create model form

- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
- select id is not correct
This commit
- fix select id
> fix: fix select id

- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/model/ConfigureModelForm.tsx
Because
- ConfigureDestinationForm's select didn't correctly display data
This commit
-  fix ConfigureDestinationForm issue
> fix: fix ConfigureDestinationForm issue

- packages/design-system/package.json
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- pnpm-lock.yaml
Because
- select can not be scrolled
This commit
- fix select scroll issue
> fix: fix select scroll issue

- packages/toolkit/src/view/model/ChangeModelStateToggle.tsx
Because
- ChangeModelStateToggle has wrong type
This commit
- fix ChangeModelStateToggle
> fix: fix ChangeModelStateToggle

- README.md
- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/model/index.ts
- packages/toolkit/src/lib/react-query-service/model/useModelReadme.ts
- packages/toolkit/src/lib/vdp-sdk/model/queries.ts
- packages/toolkit/src/lib/vdp-sdk/model/types.ts
- packages/toolkit/src/view/model/ModelCard.tsx
- packages/toolkit/src/view/model/ModelReadmeMarkdown.tsx
- packages/toolkit/src/view/model/index.ts
- pnpm-lock.yaml
Because
This commit
- add model card
> feat: add model card

- packages/toolkit/src/view/model/ModelConfigurationFields.tsx
Because
- we should disable ModelConfigurationFields
This commit
- disable ModelConfigurationFields
> fix: disable ModelConfigurationFields

- apps/cortex-playground/src/pages/index.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
Because
- create pipeline form not correctly set model.type issue
This commit
- fix this issue
> fix: fix create pipeline form not correctly set model.type issue

- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/UseExistingModelFlow.tsx
Because
- CreatePipelineForm's field id are not correct
This commit
- fix CreatePipelineForm's field id issue
> fix: fix CreatePipelineForm's field id issue

- packages/toolkit/src/components/cells/ModelsCell.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/FirstNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/LastNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/NewsletterSubscriptionField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/OrgNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/UserNameField.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelWithPresetForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/ModelBasicInputControl.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/PipelineDescriptionField.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SelectExistingDestinationFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
Because
- CreatePipelineForm async flow is not correct
This commit
-  fix CreatePipelineForm async flow
> fix: fix CreatePipelineForm async flow

- packages/toolkit/src/view/pipeline/CreatePipelineForm/FormVerticalDivider.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
Because
- the width of Setup destination step is not correct
This commit
- fix the width of setup destination step when create pipeline
> fix: fix the width of setup destination step when create pipeline

- packages/design-system/src/hooks/useRenderCounter.tsx
- packages/design-system/src/hooks/useWindowSize.tsx
- packages/design-system/src/ui/FormRoot.tsx
- packages/design-system/src/ui/InputLabels/InputLabelBase/InputLabelBase.tsx
- packages/design-system/src/ui/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx
- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
- packages/design-system/src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx
- packages/design-system/src/ui/TextFields/TextFieldBase/TextFieldBase.tsx
- packages/design-system/src/ui/TextWithHtml/TextWithHtml.tsx
- packages/design-system/src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx
- packages/design-system/src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx
Because
- The SingleSelect bgColor is wrong
This commit
- fix SingleSelect bgColor
> fix: fix SingleSelect bgColor

- apps/cortex-playground/src/pages/create-model.tsx
- packages/toolkit/src/lib/vdp-sdk/model/helper.ts
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/ModelBasicInputControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
Because
- we should not check operation status before deploy
This commit
- check controller state before deploy
> fix: check controller state before deploy

- packages/toolkit/src/lib/hook/useStateOverviewCounts.ts
Because
- useStateOverviewCount undefined issue
This commit
- fix useStateOverviewCount undefined issue
> fix: fix useStateOverviewCount undefined issue

- packages/toolkit/src/components/DeleteResourceModal.tsx
- packages/toolkit/src/lib/react-query-service/model/useModelReadme.ts
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- fix PipelinesTable typo
This commit
- fix PipelinesTable typo
> fix: fix PipelinesTable typo

- packages/toolkit/.eslintignore
- packages/toolkit/src/view/model/ConfigureModelForm.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/ModelBasicInputControl.tsx
- packages/toolkit/tsconfig.json
Because
- toolkit didn't exclude the vitest.config.ts and setupTests.ts, this cause that exported d.ts file is missing
This commit
- fix not exclude test file issue in the cortex/toolkit
> fix: fix not exclude test file issue in the cortex/toolkit

- apps/cortex-playground/src/pages/pipelines-table.tsx
- apps/cortex-playground/src/pages/sources-table.tsx
- packages/toolkit/src/components/PaginationListContainer.tsx
- packages/toolkit/src/components/cells/SkeletonCell.tsx
- packages/toolkit/src/components/cells/index.ts
- packages/toolkit/src/lib/hook/useStateOverviewCounts.ts
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- We need better loading experience
This commit
- add table loading placeholder
> feat: add table loading placeholder

- packages/toolkit/src/components/PaginationListContainer.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- table loading animation is not consistent
This commit
- fix table loading flag
> fix: fix table loading flag

- apps/cortex-playground/src/pages/pipelines-table.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- We should make the tables component act consistently
This commit
- make the input of table non-nullable
> fix: make the input of table non-nullable

- apps/cortex-playground/src/hooks/useDelayedLoading.tsx
- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/index.ts
- pnpm-lock.yaml
Because
- We need devtool to debug 
This commit
-   expose react query devtool
> feat: expose react query devtool

- apps/cortex-playground/src/pages/destinations-table.tsx
- apps/cortex-playground/src/pages/models-table.tsx
- apps/cortex-playground/src/pages/pipelines-table.tsx
- apps/cortex-playground/src/pages/sources-table.tsx
- packages/toolkit/src/lib/hook/useSearchedResources.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- Tables component will flesh when loaded
This commit
- fix tables flash issue
> fix: [INS-503] fix tables flash issue

- apps/cortex-playground/src/pages/destinations-table.tsx
- apps/cortex-playground/src/pages/models-table.tsx
- apps/cortex-playground/src/pages/pipelines-table.tsx
- apps/cortex-playground/src/pages/sources-table.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- table has loading issue due to the wrong useEffect deps
This commit
-  fix table loading issue due to the wrong useEffect deps
> fix: fix table loading issue due to the wrong useEffect deps

- apps/cortex-playground/src/pages/create-model-with-preset.tsx
- packages/toolkit/src/components/ModelDefinitionLabel.tsx
- packages/toolkit/src/components/ModelTaskLabel.tsx
- packages/toolkit/src/components/TableError.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- Together with previous PR https://github.com/instill-ai/design-system/pull/373 should create a breaking change and bump the version number
This commit
- update component api to remove all non-nullable policy
> feat: update component api to remove all non-nullable policy

- apps/cortex-playground/src/pages/destinations-table.tsx
- apps/cortex-playground/src/pages/index.tsx
- apps/cortex-playground/src/pages/models-table.tsx
- apps/cortex-playground/src/pages/pipelines-table.tsx
- apps/cortex-playground/src/pages/resource-toggle.tsx
- apps/cortex-playground/src/pages/sources-table.tsx
- packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts
Because
- we have a /user/<id>/exist endpoint
This commit
- add check user exist query
> feat: add check user exist query

- packages/toolkit/src/view/pipeline/ChangePipelineStateToggle.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- version is wrong and the package somehow didn't get published
This commit
- fix version
> fix: fix version

- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
Because
- the CreateSourceForm arg is not correct
This commit
- fix CreateSourceForm arg
> fix: fix CreateSourceForm arg

- apps/cortex-playground/src/pages/create-pipeline.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
Because
- In vdp-cloud we are going to temporarily disable creating model
This commit
- add flag to disable create model during creating pipeline
> feat: add flag to disable create model during creating pipeline

- packages/toolkit/src/lib/react-query-service/mgmt/useUpdateUser.ts
Because
- useUpdateUser not correctly sync after updating
This commit
- fix useUpdateUser not sync correctly after updating
> fix: fix useUpdateUser not correctly sync after updating

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
Because
- user configure form is not correct
This commit
- fix user configure form
> fix: fix user configure form

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
Because
- configure user info form style is wrong
This commit
- fix configure user info form style
> fix: fix configure user info form style

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
Because
- user can submit the same name under the form and cause error
This commit
- stop user from submitting the same name
> fix: stop user from submitting the same name

- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx
Because
Like the image above, the select component didn't correctly display the need height of the items
This commit
-  fix SingleSelect not correctly display its height
> fix: [INS-617] fix SingleSelect not correctly display its height

- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
Because
-  we want to fully disable model creation
This commit
- update the style when disable model creation
> chore: update the style when disable model creation

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/FirstNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/LastNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/OrgNameField.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/UserNameField.tsx
Because
- ConfigureProfileForm is incorrect
This commit
- fix configure user profile incorrectly set value
> fix: fix configure user profile incorrectly set value

- apps/cortex-playground/src/pages/configure-user.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
Because
- role field is not correct
This commit
- fix role not correctly pick
> fix: fix role not correctly pick

- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileForm.tsx
- pnpm-lock.yaml
Because
- We let consumer decide how to style the avatar of configure profile form
This commit
- remove the unused profile avatar on configure profile form
> chore: remove the unused profile avatar on configure profile form

- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/connector/destination/index.ts
- packages/toolkit/src/lib/react-query-service/connector/destination/prefetchDestinations.ts
- packages/toolkit/src/lib/react-query-service/connector/destination/useDestinations.ts
- packages/toolkit/src/lib/react-query-service/connector/source/index.ts
- packages/toolkit/src/lib/react-query-service/connector/source/prefetchSources.ts
- packages/toolkit/src/lib/react-query-service/connector/source/useSources.ts
- packages/toolkit/src/lib/react-query-service/model/index.ts
- packages/toolkit/src/lib/react-query-service/model/prefetchModels.ts
- packages/toolkit/src/lib/react-query-service/model/useModels.ts
- packages/toolkit/src/lib/react-query-service/pipeline/index.ts
- packages/toolkit/src/lib/react-query-service/pipeline/prefetchPipelines.ts
- packages/toolkit/src/lib/react-query-service/pipeline/usePipelines.ts
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModeStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
Because
- There are multiple loading state when create pipeline
This commit
- add prefetch resources function and prefetch resource in create pipeline form
> feat: add prefetch resources function and prefetch resource in create pipeline form

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- pnpm-lock.yaml
Because
- in pipeline recipe's component, the id should be determined by client
This commit
- fix createPipelineForm not generate unique uuid
> fix: fix createPipelineForm not generate unique uuid

- packages/toolkit/src/lib/react-query-service/connector/destination/useDestinationWithPipelines.ts
- packages/toolkit/src/lib/react-query-service/connector/destination/useDestinationsWithPipelines.ts
- packages/toolkit/src/lib/react-query-service/connector/source/useSourceWithPipelines.ts
- packages/toolkit/src/lib/react-query-service/connector/source/useSourcesWithPipelines.ts
- packages/toolkit/src/lib/react-query-service/model/index.ts
- packages/toolkit/src/lib/react-query-service/model/useModelWithPipelines.ts
- packages/toolkit/src/lib/vdp-sdk/model/types.ts
Because
- we should correctly get the pipelines that use this resoruce
This commit
- fix not correctly query pipelines that use this resource
> fix: fix not correctly query pipelines that use this resource

- apps/cortex-playground/src/pages/_app.tsx
- apps/cortex-playground/src/pages/_document.tsx
- apps/cortex-playground/src/pages/index.tsx
- packages/design-tokens/README.md
- packages/design-tokens/src/buildStyleDictionary.ts
- packages/design-tokens/src/buildTailwindPlugin.ts
Because
- We have to document about how we construct the design-tokens
This commit
- Add docs about design tokens
> feat(docs): [INS-829] Add docs about design tokens

- package.json
- release-please/manifest.json
- turbo.json
Because
- The build script and turbo configuration didn't indicate the pipeline correctly
This commit
- fix the build script and deps in turbo pipeline
> chore(cortex): fix the build script and deps in turbo pipeline

- apps/cortex-playground/src/pages/index.tsx
- packages/design-tokens/README.md
- packages/design-tokens/src/buildCSSVariables.ts
- packages/design-tokens/src/buildSDTokens.ts
- packages/design-tokens/src/buildTailwindPreset.ts
- packages/design-tokens/src/type.ts
- pnpm-lock.yaml
Because
- edge cases like fontStyle, textCase, letterSpacing will cause error in the design tokens
This commit
- transform fontStyle, textCase, letterSpacing edge case
> fix(design-tokens): transform fontStyle, textCase, letterSpacing edge cases

- packages/design-system/src/new-ui/Icons/Database01.tsx
- packages/design-system/src/new-ui/Icons/Icons.stories.tsx
- packages/design-system/src/new-ui/Icons/Model.tsx
- packages/design-system/src/new-ui/Icons/Pipeline.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We have new icons
This commit
- add new model and pipeline icon
> feat(design-system): add new model and pipeline icon

- packages/design-tokens/README.md
Because
- We have better design-tokens preface
This commit
- update design-tokens preface
> docs(design-tokens): update design-tokens preface

- apps/cortex-playground/src/pages/configure-destination.tsx
- apps/cortex-playground/src/pages/configure-source.tsx
- apps/cortex-playground/tailwind.config.js
- packages/toolkit/package.json
- packages/toolkit/src/lib/vdp-sdk/connector/destination/actions.ts
- packages/toolkit/src/lib/vdp-sdk/connector/destination/index.ts
- packages/toolkit/src/lib/vdp-sdk/connector/source/actions.ts
- packages/toolkit/src/lib/vdp-sdk/connector/source/index.ts
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/RoleField.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SelectExistingModelFlow.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- pnpm-lock.yaml
Because
- We want to have the ability to test connector connection
This commit
- add test connector connection button
> feat(toolkit): add test connector connection button

- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
Because
- test connection action is incorrectly disabled
This commit
- fix test connection action incorrectly disabled
> fix(toolkit): fix test connection action incorrectly disabled

- apps/cortex-playground/package.json
- apps/cortex-playground/src/pages/_app.tsx
- apps/cortex-playground/src/pages/create-source.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SelectExistingDestinationFlow.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
- pnpm-lock.yaml
Because
- react-query instance will cause hook rerender
This commit
- fix react-query instance cause hook re-render issue
> fix: fix react-query instance cause hook re-render issue

- apps/cortex-playground/src/pages/configure-destination.tsx
- apps/cortex-playground/src/pages/create-model-with-preset.tsx
- apps/cortex-playground/src/pages/create-model.tsx
- apps/cortex-playground/src/pages/create-source.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelWithPresetForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/InputModelBasicInfoCard.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/ModelBasicInputControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDestinationStep/SetPipelineDestinationStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineModelStep/SetPipelineModelStep.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
Because
- Unify the API of the components
This commit
- remove all the initStoreOn... props
> chore: remove all the initStoreOn... props

- apps/cortex-playground/src/pages/configure-destination.tsx
- apps/cortex-playground/src/pages/configure-source.tsx
- apps/cortex-playground/src/pages/create-model-with-preset.tsx
- apps/cortex-playground/src/pages/create-model.tsx
- apps/cortex-playground/src/pages/create-pipeline.tsx
- apps/cortex-playground/src/pages/create-source.tsx
- packages/toolkit/src/lib/react-query-service/connector/destination/useUpdateDestination.ts
- packages/toolkit/src/lib/react-query-service/model/useUpdateModel.ts
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/destination/CreateDestinationForm.tsx
- packages/toolkit/src/view/model/ConfigureModelForm.tsx
- packages/toolkit/src/view/model/CreateModelForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/CreateModelWithPresetForm.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/InputModelBasicInfoCard.tsx
- packages/toolkit/src/view/model/CreateModelWithPresetForm/InputModelBasicInfoCard/ModelBasicInputControl.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
- packages/toolkit/src/view/pipeline/ConfigurePipelineForm/ConfigurePipelineFormControl.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/CreatePipelineForm.tsx
- packages/toolkit/src/view/pipeline/CreatePipelineForm/SetPipelineDetailsStep.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceForm.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceControl.tsx
Because
- configure resource form is not correct
This commit
-  fix several issues related to configure resource
> fix: fix several issues related to configure resource

- packages/toolkit/package.json
- packages/toolkit/src/components/PageBase.tsx
- packages/toolkit/src/components/index.ts
- packages/toolkit/tailwind.config.js
- pnpm-lock.yaml
Because
- Centralize components
This commit
- add PageBase component into toolkit
> feat: add PageBase component into toolkit

- packages/design-tokens/tokens/semantic/colour.json
- packages/design-tokens/tokens/theme/dark.json
- packages/design-tokens/tokens/theme/light.json
Because
- Some tokens where missing on the semantic and theme level
This commit
- add missing tokens
- Fix wrong colour assignment on dark theme success
> fix(design-tokens): fix missing tokens

- packages/design-system/.storybook/preview.js
- packages/design-system/package.json
- packages/design-system/src/new-ui/Textarea/Textarea.stories.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.tsx
- packages/design-system/src/new-ui/Textarea/index.ts
- packages/design-system/tailwind.config.cjs
- pnpm-lock.yaml
Because
- we are re-designing the design-system
This commit
- add new Textarea component
> feat(design-system): add new Textarea component

- packages/design-system/.storybook/main.ts
- packages/design-system/.storybook/preview.ts
- packages/design-system/src/new-ui/Dialog/Dialog.stories.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.stories.tsx
Because
- storybook build will fall on prod
This commit
- fix storybook build issue
> fix(design-system): fix storybook build issue

- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/SourceDefinitionField.tsx
Because
- ConfigureSourceForm source input type is wrong
This commit
- fix ConfigureSourceForm source input type
> fix(toolkit): fix ConfigureSourceForm source input type

- packages/design-system/package.json
- packages/design-tokens/package.json
- packages/toolkit/package.json
- packages/toolkit/postcss.config.cjs
- pnpm-lock.yaml
Because
- TailwindCSS version need to bump to above 3.2.0 to use the data-attribute
This commit
- update tailwindcss version
> chore(cortex): update tailwindcss version

- packages/design-system/.storybook/main.ts
- packages/design-system/.storybook/preview-head.html
- packages/design-system/.storybook/preview.ts
- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/postcss.config.cjs
- packages/design-system/public/tailwind.css
- packages/design-system/src/styles/global.css
- pnpm-lock.yaml
Because
- The storybook can't correctly import tailwind CSS
This commit
- update how we handle import tailwindcss style to storybook
> chore(design-system): update how we handle import tailwindcss style to storybook

- packages/design-system/package.json
- packages/design-system/public/tailwind.css
- packages/design-system/src/new-ui/Dialog/Dialog.stories.tsx
- packages/design-system/src/new-ui/Switch/Switch.stories.tsx
- packages/design-system/src/new-ui/Switch/Switch.tsx
- packages/design-system/src/new-ui/Switch/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- Implement new design system
This commit
- implement new switch
> feat(design-system): implement new switch

- packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx
- packages/design-system/src/ui/SingleSelects/SingleSelectBase/SelectItem.tsx
Because
- We need accurate way to get the select item
This commit
- add data-testid in BasicSingleSelect
> chore(design-system): add data-testid in BasicSingleSelect

- .gitignore
- packages/design-system/src/new-ui/Input/Input.stories.tsx
- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Input/index.ts
- packages/design-system/src/new-ui/Textarea/Textarea.stories.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.tsx
- packages/design-system/src/new-ui/index.ts
Because
- We have several new components
This commit
- implement the new Input component
> feat(design-system): implement the new Input component

- packages/design-system/src/new-ui/Field.tsx
- packages/design-system/src/new-ui/Input/Input.stories.tsx
- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Switch/Switch.stories.tsx
- packages/design-system/src/new-ui/Switch/Switch.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.stories.tsx
- packages/design-system/src/new-ui/index.ts
Because
- We use Field component to assemble a form's field
This commit
- add Field component
> feat(design-system): add Field component

- packages/design-system/package.json
- packages/design-system/src/new-ui/Form/Form.stories.tsx
- packages/design-system/src/new-ui/Form/Form.tsx
- packages/design-system/src/new-ui/Form/index.ts
- packages/design-system/src/new-ui/Input/Input.stories.tsx
- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Label.tsx
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- We will use react-hook-form to handle the form in the future
This commit
- implement new Form component
> feat(design-system): implement new Form component

- packages/design-system/README.md
- packages/design-system/src/new-ui/Form/Form.stories.tsx
- packages/design-system/src/new-ui/Form/Form.tsx
Because
- We need to show the form error message
This commit
- add form message
> feat(design-system): add form message

- packages/design-system/src/new-ui/Icons/Check.tsx
- packages/design-system/src/new-ui/Icons/index.ts
- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Select/Select.stories.tsx
- packages/design-system/src/new-ui/Select/Select.tsx
- packages/design-system/src/new-ui/Select/index.ts
- packages/design-system/src/new-ui/index.ts
Because
- We need new component for Select
This commit
- add the Select component
> feat(design-system): add the Select component

- packages/design-system/package.json
- packages/design-system/src/new-ui/Button/Button.stories.tsx
- packages/design-system/src/new-ui/Button/Button.tsx
- packages/design-system/src/new-ui/Button/index.ts
- packages/design-system/src/new-ui/Input/Input.stories.tsx
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- We have better way to implement button
This commit
- implement new button component
> feat(design-system): implement new button component

- packages/design-system/src/new-ui/Button/Button.tsx
- packages/design-system/src/new-ui/LinkButton/LinkButton.stories.tsx
- packages/design-system/src/new-ui/LinkButton/LinkButton.tsx
- packages/design-system/src/new-ui/LinkButton/index.ts
- packages/design-system/src/new-ui/index.ts
Because
- We are refactoring design system
This commit
- add LinkButton component
> feat(design-system): add LinkButton component

- packages/design-system/package.json
- packages/design-system/src/new-ui/Button/Button.stories.tsx
- packages/design-system/src/new-ui/Separator/Separator.stories.tsx
- packages/design-system/src/new-ui/Separator/Separator.tsx
- packages/design-system/src/new-ui/Separator/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- we need unify separator
This commit
- implement Separator component
> feat(design-system): implement Separator component

- packages/design-system/src/new-ui/Dialog/Dialog.stories.tsx
- packages/design-system/src/new-ui/Dialog/Dialog.tsx
- packages/design-system/src/new-ui/Form/Form.stories.tsx
- packages/design-system/src/new-ui/Form/Form.tsx
Because
- Dialog is not complete
This commit
- Add DialogClose component
- Update the DialogTitle and DialogDescription style
- Rename FormProvider to FormRoot
> feat(design-system): Dialog is not complete

- packages/design-system/package.json
- packages/toolkit/package.json
Because
- design-systme and toolkit peerDeps are wrong
This commit
- fix design-systme and toolkit peerDeps
> fix(design-system)(toolkit): fix design-systme and toolkit peerDeps

- packages/design-system/src/new-ui/Select/Select.stories.tsx
- packages/design-system/src/new-ui/Select/Select.tsx
Because
- The select need to use group to control the hover effect
This commit
- add group attribute into Select
> feat(design-system): add group attribute into Select

- packages/design-system/src/new-ui/Dialog/Dialog.tsx
- packages/design-system/src/new-ui/Icons/AlertCircle.tsx
- packages/design-system/src/new-ui/Icons/AlertTriangle.tsx
- packages/design-system/src/new-ui/Icons/BarChartSquare02.tsx
- packages/design-system/src/new-ui/Icons/Box.tsx
- packages/design-system/src/new-ui/Icons/Check.tsx
- packages/design-system/src/new-ui/Icons/CheckCircle.tsx
- packages/design-system/src/new-ui/Icons/ChevronDown.tsx
- packages/design-system/src/new-ui/Icons/ChevronUp.tsx
- packages/design-system/src/new-ui/Icons/Chip01.tsx
- packages/design-system/src/new-ui/Icons/Chip02.tsx
- packages/design-system/src/new-ui/Icons/Cube01.tsx
- packages/design-system/src/new-ui/Icons/Database01.tsx
- packages/design-system/src/new-ui/Icons/Edit05.tsx
- packages/design-system/src/new-ui/Icons/Gear01.tsx
- packages/design-system/src/new-ui/Icons/HelpCircle.tsx
- packages/design-system/src/new-ui/Icons/IconBase/IconBase.tsx
- packages/design-system/src/new-ui/Icons/InfoCircle.tsx
- packages/design-system/src/new-ui/Icons/Logout01.tsx
- packages/design-system/src/new-ui/Icons/Model.tsx
- packages/design-system/src/new-ui/Icons/Pipeline.tsx
- packages/design-system/src/new-ui/Icons/Play.tsx
- packages/design-system/src/new-ui/Icons/Plus.tsx
- packages/design-system/src/new-ui/Icons/Save01.tsx
- packages/design-system/src/new-ui/Icons/Sliders01.tsx
- packages/design-system/src/new-ui/Icons/X.tsx
Because
- Icons didn't have correct displayName
This commit
- fix Icons displayName issue
> fix(design-system): fix Icons displayName issue

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
Because
- duplicated key at ConfigureAIForm
This commit
-  fix duplicated key at ConfigureAIForm
> fix(toolkit): fix duplicated key

- packages/toolkit/package.json
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
Because
- Add more control into form
This commit
- add multiple on action at ConfigureAIForm
> chore(toolkit): add multiple on action at ConfigureAIForm

- .github/workflows/release.yml
- packages/design-system/README.md
- packages/toolkit/README.md
Because
- release workflow is not correct
This commit
- fix release workflow
> fix: fix release workflow

- packages/toolkit/src/view/blockchan/BlockchainTablePlaceholder.tsx
- packages/toolkit/src/view/blockchan/BlockchainsTable.tsx
- packages/toolkit/src/view/blockchan/index.ts
Because
- We will have blockchain page 
This commit
- add BlockchainsTable
> feat(toolkit): add BlockchainsTable

- packages/toolkit/src/lib/amplitude/type.ts
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/index.ts
Because
- Centralize components
This commit
- add ConfigureBlockchainForm
> feat(toolkit): add ConfigureBlockchainForm

- apps/cortex-playground/.env
- packages/toolkit/src/components/cells/TextCell.tsx
- packages/toolkit/src/components/cells/index.ts
- packages/toolkit/src/lib/react-query-service/connector/useUpdateConnector.ts
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- when getComponentsFromPipelineRecipe doesn't get data it will cause error
This commit
- fix getComponentsFromPipelineRecipe not getting data and cause error
> fix: fix getComponentsFromPipelineRecipe not getting data and cause error

- packages/toolkit/src/lib/react-query-service/connector/index.ts
- packages/toolkit/src/lib/react-query-service/connector/useConnectConnector.ts
- packages/toolkit/src/lib/react-query-service/connector/useDisonnectConnector.ts
- packages/toolkit/src/lib/react-query-service/model/useUnDeployModel.ts
- packages/toolkit/src/lib/vdp-sdk/connector/actions.ts
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
Because
- We need to connect/disconnect connector
This commit
- add dis/connect connector SDK
> feat(toolkit): add dis/connect connector SDK

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
Because
- Configure AI and Blockchain won't update field values after updated
This commit
- fix configure ai and blockchain form not update the value
> fix: fix configure ai and blockchain form not update the value

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx
Because
- numbers-blockchain-nit -> blockchain-numbers
- instill-ai-model-> ai-instill-model
- stability-ai-model -> ai-stability-ai
- blockchain remove creator_name and license field
This commit
- update the changes of connector
> feat(toolkit): update the changes of connector

- packages/design-system/src/new-ui/Icons/ChevronDownDouble.tsx
- packages/design-system/src/new-ui/Icons/ChevronLeft.tsx
- packages/design-system/src/new-ui/Icons/ChevronLeftDouble.tsx
- packages/design-system/src/new-ui/Icons/ChevronRight.tsx
- packages/design-system/src/new-ui/Icons/ChevronRightDouble.tsx
- packages/design-system/src/new-ui/Icons/ChevronUpDouble.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- Centralize icons
This commit
- add chev icons
> feat: add chev icons

- packages/toolkit/package.json
- packages/toolkit/src/components/CodeBlock.tsx
- packages/toolkit/src/components/index.ts
- pnpm-lock.yaml
Because
- We need CodeBlock component 
This commit
- add SyntaxHighlighter CodeBlock
> feat: add SyntaxHighlighter CodeBlock

- packages/toolkit/src/lib/react-query-service/pipeline/useActivatePipeline.ts
- packages/toolkit/src/lib/react-query-service/pipeline/useDeActivatePipeline.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts
Because
- wrongly cache activate/deactivate pipeline response
This commit
- fix wrongly cache activate/deactivate pipeline response
> fix: fix wrongly cache activate/deactivate pipeline response

- packages/toolkit/src/lib/react-query-service/connector/useWatchConnector.ts
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
Because
- User need to connect connector on its page
This commit
- add connect button in connector pages
> feat: add connect button in connector pages

- packages/design-system/package.json
- packages/design-system/prettier.config.cjs
- packages/design-system/src/new-ui/Form/Form.tsx
- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Label.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.tsx
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- pnpm-lock.yaml
Because
- We need to have a unified style
This commit
- unify text color across different form component
> fix(toolkit,design-system): unify text color across different form component

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/PipelineForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/triggerPipelineSnippets.ts
Because
- We should have trigger snippet for CE
This commit
- update the pipeline trigger snippet for CE
> feat: update the pipeline trigger snippet for CE

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
Because
- We have new ai connector definition related to field's description
This commit
- update ai connector definition
> feat: update ai connector definition

- packages/toolkit/src/components/cells/TextCell.tsx
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
Because
- We have new blockchain connector definition
This commit
- update blockchain/ai connector definition
> feat(toolkit): update blockchain/ai connector definition

- packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx
Because
- Visual bug
This commit
- don't show ai task for preset
> feat: don't show ai task for preset

- packages/toolkit/src/lib/pipeline-builder/getConnectorPresets.ts
- packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/SelectConnectorDefinitionDialog.tsx
Because
- Preset name at left panel is not correct
This commit
- fix wrong preset name at left panel
> fix(toolkit): fix wrong preset name at left panel

- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Select/Select.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.tsx
Because
- We need to make form style consistent
This commit
- make form and input bg color to be primary white
> feat(design-system): make form and input bg color to be primary white

- packages/toolkit/src/view/pipeline-builder/PipelineNameForm.tsx
- packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/PipelineForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/RightPanel.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
Because
- Some of accessToken and enableQuery not correctly pass down
This commit
-  fix accessToken and enableQuery not correctly pass down
> fix: fix accessToken and enableQuery not correctly pass down

- packages/design-system/src/new-ui/Input/Input.tsx
- packages/design-system/src/new-ui/Textarea/Textarea.tsx
- packages/design-system/src/new-ui/Toast/Toaster.tsx
Because
- disabled input color is not correct
This commit
- fix disabled input bg-color
> fix: fix disabled input bg-color

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx
Because
- we need a indicator to indicate loading spin
This commit
- add pipeline-builder main loading spin
> feat(toolkit): add pipeline-builder main loading spin

- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
Because
- left panel can't scroll
This commit
- fix left panel scroll issue
> fix: fix left panel scroll issue

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/blockchan/ConfigureBlockchainForm.tsx
- packages/toolkit/src/view/destination/ConfigureDestinationForm.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/ConfigureSourceControl.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/SourceDefinitionField.tsx
Because
- Users can not modify connectors provided by Instill AI
This commit
-  disable all the actions toward public connector
> fix: disable all the actions toward public connector

- packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx
Because
- User should have the agency to clean up unsaved form
This commit
- let user clean up unsaved form
> feat: let user clean up unsaved form

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/PipelineForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/RightPanel.tsx
- packages/toolkit/tailwind.config.js
- pnpm-lock.yaml
Because
- Add save button at the right panel
- fix multiple typo
> feat(toolkit): Add save button at the right panel

- packages/toolkit/src/view/pipeline-builder/right-panel/PipelineForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/RightPanel.tsx
Because
- we don't want to have duplicated save button
This commit
- remove duplicated save button
> fix: remove duplicated save button

- packages/design-system/src/new-ui/Switch/Switch.stories.tsx
- packages/design-system/src/new-ui/Switch/Switch.tsx
Because
- switch color is not correct
This commit
- fix switch color
> fix: fix switch color

- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
Because
- We need to indicate these action is operating
This commit
- update save pipeline button to have better loading state
> feat: update save pipeline button to have better loading state

- packages/design-system/src/new-ui/Toast/Toast.tsx
- packages/design-system/src/new-ui/Toast/use-toast.tsx
Because
- Some moment we need to display multiple toasts
This commit
-  increase the limit of toast to 3
> feat: increase the limit of toast to 3

- packages/toolkit/src/lib/store/usePipelineBuilderStore.ts
- packages/toolkit/src/view/ai/AITablePlaceholder.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
Because
- Improve UX
This commit
- save pipeline before activate/deactivate
> feat(toolkit): save pipeline before activate/deactivate

- packages/toolkit/package.json
- packages/toolkit/src/lib/store/usePipelineBuilderStore.ts
- packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.css
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
- pnpm-lock.yaml
Because
- pipelineBuilderStore pipelineRecipeIsDirty setter not correctly update state
This commit
-  fix pipelineBuilderStore pipelineRecipeIsDirty setter issue
> fix(toolkit): fix pipelineBuilderStore pipelineRecipeIsDirty setter issue

- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/view/pipeline-builder/flow/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/AINode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/BlockchainNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/DestinationNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/SourceNode.tsx
Because
- rename pipeline has some issue
This commit
- fix rename issue
> fix(toolkit): fix rename issue

- packages/toolkit/src/lib/store/usePipelineBuilderStore.ts
- packages/toolkit/src/view/pipeline-builder/PipelineNameForm.tsx
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/DestinationForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/PipelineForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
Because
- There are unnecessary fetch in pipeline builder
This commit
- fix unnecessary fetch in pipeline-builder
> fix(toolkit): fix unnecessary fetch in pipeline-builder

- packages/design-system/package.json
- packages/design-system/src/new-ui/Tooltip/Tooltip.stories.tsx
- packages/design-system/src/new-ui/Tooltip/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- we need a tooltip component 
This commit
- tooltip component
> feat: tooltip component for design-system INS-1163

- packages/design-system/src/new-ui/Button/Button.tsx
- packages/design-system/src/new-ui/LinkButton/LinkButton.tsx
- packages/design-system/src/new-ui/TagButton/TagButton.stories.tsx
- packages/design-system/src/new-ui/TagButton/TagButton.tsx
- packages/design-system/src/new-ui/TagButton/index.ts
- packages/design-system/src/new-ui/index.ts
Because
-we need <TagButton /> component
This commit
- <TagButton /> component
> feat: namananand/create tagbutton for design system

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
Because
- we have new node style
This commit
- implement the new node style
> feat(tooltip): implement the new node style

- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/new-ui/Button/Button.tsx
- packages/design-system/src/new-ui/LinkButton/LinkButton.tsx
- packages/design-system/src/new-ui/TagButton/TagButton.stories.tsx
- packages/design-system/src/new-ui/TagButton/TagButton.tsx
- packages/design-system/src/new-ui/TagButton/index.ts
- packages/design-system/src/new-ui/index.ts
- packages/toolkit/README.md
- packages/toolkit/package.json
- packages/toolkit/src/lib/pipeline-builder/constructPipelineRecipe.tsx
- packages/toolkit/src/lib/pipeline-builder/createInitialGraphData.tsx
- packages/toolkit/src/lib/pipeline-builder/parseDependencyComponents.ts
- packages/toolkit/src/view/pipeline-builder/flow/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/AINode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/BlockchainNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.css
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/DestinationNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/SourceNode.tsx
- release-please/manifest.json
Because
- We have new pipeline builder to support much advanced use case
This commit
- implement new multiple handlers pipeline builder
> feat(toolkit): implement new multiple handlers pipeline builder

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- We will support new task for Stability AI connector
This commit
- add Image to Image task into Stability AI connector
> feat(toolkit): add Image to Image task into Stability AI connector

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- We will support openai connector
This commit
- support openai connector
> feat(toolkit): support openai connector

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- we support extra model 
This commit
- add support stability AI SDXL model
> feat: add support stability AI SDXL model

- packages/design-system/package.json
- packages/design-system/src/new-ui/Checkbox/Checkbox.stories.tsx
- packages/design-system/src/new-ui/Checkbox/Checkbox.tsx
- packages/design-system/src/new-ui/Checkbox/index.ts
- packages/design-system/src/new-ui/Tag/Tag.tsx
- packages/design-system/src/new-ui/TagButton/TagButton.tsx
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- we need `<Checkbox />` component
This commit
- `<Checkbox />` component
> feat: checkbox component

- packages/design-system/src/new-ui/Table/Table.stories.tsx
- packages/design-system/src/new-ui/Table/Table.tsx
- packages/design-system/src/new-ui/Table/index.ts
- packages/design-system/src/new-ui/index.ts
Because
- we need `<Table />` component to build `<DataTable /> `
This commit
- `<Table />` component
> feat: component from shacdnui for the table

- packages/toolkit/src/view/pipeline-builder/nodes/AINode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/BlockchainNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/DestinationNode.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/SourceNode.tsx
Because
- Improve UX
This commit
-  update the node style and disable one side of trigger/response handler
> feat: update the node style and disable one side of trigger/response handler

- packages/toolkit/src/components/cells/Cell.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx
- packages/toolkit/src/view/dashboard/PipelineTriggersTable.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
Because
- Improve UX
This commit
- add query param to pre-fill the field of AI connector
> feat(toolkit): add query param to pre-fill the field of AI connector

- packages/design-system/src/new-ui/Button/Button.stories.tsx
Because
- we need sorting button example
This commit
- sorting button example
> feat: sorting button example

- packages/design-system/src/new-ui/DataTable/DataTablePagination.tsx
Because
- pagination border not correct
This commit
- pagination border
> fix(design-system): fix data-table pagination button border

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- We have new model task icons
This commit
- update model task icons in AI related fields
> chore(toolkit): update model task icons in AI related fields

- pnpm-lock.yaml
Because
- update pnpm-lock is not correct
This commit
- update pnpm-lock
> feat: update pnpm-lock

- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/BlockchainForm.tsx
Because
- public connector not disabled issue
This commit
- fix public connector not disabled issue
> fix(toolkit): fix public connector not disabled issue

- packages/toolkit/src/components/cells/GeneralStateCell.tsx
- packages/toolkit/src/lib/dashboard/convertTimestamp.ts
- packages/toolkit/src/lib/dashboard/convertToSecondsAndMilliseconds.ts
- packages/toolkit/src/lib/dashboard/index.ts
- packages/toolkit/src/lib/dashboard/parseTriggerStatusLabel.ts
- packages/toolkit/src/view/dashboard/PipelineTriggersSummary.tsx
- packages/toolkit/src/view/dashboard/PipelineTriggersTable.tsx
Because
- need to trigger pipeline specific fix
This commit
- trigger pipeline specific fix
> fix(toolkit): trigger pipeline specific fix

- packages/toolkit/src/lib/dashboard/formatDateTime.ts
- packages/toolkit/src/lib/dashboard/index.ts
- packages/toolkit/src/lib/dashboard/xAxisRange.ts
- packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- chart trigger count not correct
This commit
- trigger count correction
> fix(toolkit): chart trigger count fix

- packages/design-system/src/ui-helpers/getModelInstanceTaskToolkit.tsx
Because
- need to add text Embeddings label
This commit
- added text Embeddings label
> fix(design-system): text Embeddings label add

- packages/toolkit/src/view/dashboard/FilterByDay.tsx
Because
- refresh button not have correct css
This commit
- correct css for refresh button
> fix(design-system): refresh button fix

- packages/toolkit/src/view/ai/index.ts
- packages/toolkit/src/view/blockchan/CreateBlockchainForm.tsx
- packages/toolkit/src/view/blockchan/index.ts
Because
- table placeholder export
This commit
- table placeholder export
> fix: table placeholder export

- packages/design-system/src/new-ui/Icons/SearchSm.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- we need search icon
This commit
- search icon
> feat(design-system): search icon

- packages/design-system/src/new-ui/Icons/Circle.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- need circle icon
This commit
- circle icon
> feat(design-system): circle icon

- packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx
- packages/toolkit/src/view/dashboard/FilterByDay.tsx
Because
- url fix for dashboard
This commit
- url fix for dashboard
> fix(toolkit): url fix for dashboard

- packages/design-system/src/new-ui/DataTable/DataTable.stories.tsx
- packages/design-system/src/new-ui/DataTable/DataTable.tsx
- packages/design-system/src/new-ui/DataTable/DataTablePagination.tsx
- packages/design-system/src/new-ui/Table/Table.tsx
Because
- we need to add search and table primary and secondary text
This commit
- search and table primary and secondary text
> feat(design-system): add search and table primary and secondary text

- packages/design-system/src/new-ui/Icons/SpeechRecognition.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- SpeechRecognition icon
This commit
- SpeechRecognition icon
> feat(design-system): SpeechRecognition icon

- packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx
- packages/toolkit/src/view/dashboard/FilterByDay.tsx
Because
- after refresh the day value reset to today
This commit
- after refresh the day value reset to today
> fix: Namananand/ins 1413 after refresh the day value reset to today

- packages/toolkit/src/lib/dashboard/calculatePercentageDelta.ts
Because
- delta changes calculation
This commit
- delta changes calculation
> fix: delta changes calculation

- packages/toolkit/src/lib/dashboard/calculatePercentageDelta.ts
Because
- chart change not correct
This commit
- chart change not correct
> fix: namananand/ins 1412 dashboard chart change not correct

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
Because
- update OpenAI AI Connector creation form
This commit
- update OpenAI AI Connector creation form
> feat: update OpenAI AI Connector creation form

- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/view/ai/AIsTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- pipeline and ai table add delete model
This commit
- pipeline and ai table add delete model
> chore: pipeline and ai table add delete model

- packages/toolkit/src/lib/vdp-sdk/connector/types.ts
Because
- update connector type
This commit
- update connector type
> chore: update connector type

- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/components/index.ts
- packages/toolkit/src/lib/vdp-sdk/connector/types.ts
Because
- export fix
This commit
- export fix
> fix(toolkit): export fix

- packages/toolkit/src/components/DeleteResourceModal.tsx
- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/lib/pipeline-builder/createInitialGraphData.tsx
- packages/toolkit/src/lib/pipeline-builder/getConnectorPresets.ts
- packages/toolkit/src/lib/vdp-sdk/connector/types.ts
- packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/LeftPanel.tsx
- packages/toolkit/src/view/pipeline-builder/left-panel/SelectConnectorDefinitionDialog.tsx
- packages/toolkit/src/view/pipeline-builder/left-sidebar/LeftSidebar.tsx
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/RightPanel.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/SourceForm.tsx
- packages/toolkit/src/view/pipeline/PipelineTable.tsx
- packages/toolkit/src/view/source/ConfigureSourceForm/SourceDefinitionField.tsx
- packages/toolkit/src/view/source/CreateSourceForm/CreateSourceForm.tsx
- packages/toolkit/src/view/source/CreateSourceForm/index.ts
Because
- update CONNECTOR_TYPE_SOURCE to CONNECTOR_TYPE_OPERATOR
This commit
- update CONNECTOR_TYPE_SOURCE to CONNECTOR_TYPE_OPERATOR
> chore(toolkit): update CONNECTOR_TYPE_SOURCE to CONNECTOR_TYPE_OPERATOR 

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/dnd/Draggable.tsx
Because
- update label for operators
This commit
- update label for operators
> chore: update label for operators

- packages/toolkit/src/lib/pipeline-builder/constructPipelineRecipe.tsx
- packages/toolkit/src/lib/pipeline-builder/createInitialGraphData.tsx
- packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
- packages/toolkit/src/view/pipeline-builder/nodes/CustomNode.tsx
Because
- support audios node
This commit
- support audios node
> chore: support audios node

- packages/design-system/src/ui-helpers/getModelInstanceTaskToolkit.tsx
- packages/toolkit/src/view/ai/AIsTable.tsx
Because
- AIs table fix
This commit
- AIs table fix
> fix(toolkit): AIs table fix

- packages/toolkit/src/lib/pipeline-builder/constructPipelineRecipe.tsx
Because
- update pipeline component dependency
This commit
- update pipeline component dependency
> fix: update pipeline component dependency

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- update label
This commit
- update label
> fix(toolkit): update label AI form

- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- update engine for stability AI
This commit
- update engine for stability AI
> chore(toolkit): update engine for stability AI

- packages/design-system/src/new-ui/DataTable/DataTablePagination.tsx
Because
- add pagination for long pages
This commit
- add pagination for long pages
> chore(design-system): add pagination for long pages

- packages/design-system/src/new-ui/DataTable/DataTablePagination.tsx
- packages/toolkit/src/components/cells/GeneralTaskCell.tsx
- packages/toolkit/src/view/ai/AIsTable.tsx
- packages/toolkit/src/view/ai/ConfigureAIForm.tsx
- packages/toolkit/src/view/ai/CreateAIForm.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- small fixes for AI, model and Pipeline table
This commit
- small fixes for AI, model and Pipeline table
> fix(toolkit): small fixes for AI, model and Pipeline table

- packages/design-system/src/new-ui/DataTable/DataTablePagination.tsx
Because
- datatable pagination
This commit
- datatable pagination
> fix(design-system): datatable pagination

- packages/toolkit/src/view/pipeline-builder/right-panel/AIForm.tsx
Because
- Speech Recognition form select
This commit
- Speech Recognition form select
> fix(toolkit): Speech Recognition form select

- packages/toolkit/src/view/ai/AIsTable.tsx
Because
- column size fix
This commit
- column size fix
> fix(toolkit): column size fix

- packages/toolkit/src/view/ai/AIsTable.tsx
Because
- AI table column size
This commit
- AI table column size
> fix(toolkit): AI table column size

- packages/design-system/src/new-ui/DataTable/DataTable.tsx
Because
- cancel button for table search
This commit
- cancel button for table search
> chore(design-system): cancel button for table search

- packages/design-system/src/new-ui/DataTable/DataTable.tsx
Because
- update cancel search
This commit
- update cancel search
> chore: namananand/ins 1478 search also dont have cancel icon to remove search string

- packages/design-system/src/new-ui/Checkbox/Checkbox.stories.tsx
- packages/design-system/src/new-ui/Checkbox/Checkbox.tsx
Because
- Expand the functionality of checkbox
This commit
- add RoundedCheck
> feat: add RoundedCheck

- packages/design-system/package.json
- packages/design-system/src/new-ui/Popover/Popover.stories.tsx
- packages/design-system/src/new-ui/Popover/Popover.tsx
- packages/design-system/src/new-ui/Popover/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- add popover component
This commit
- add popover component
> feat(design-system): add popover component

- packages/toolkit/src/view/ai/AIsTable.tsx
- packages/toolkit/src/view/blockchain/BlockchainsTable.tsx
- packages/toolkit/src/view/destination/DestinationsTable.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/source/SourcesTable.tsx
Because
- update all table props accessToken
This commit
- update all table props accessToken
> chore(toolkit): update all table props accessToken

- packages/design-system/src/new-ui/Icons/Edit03.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We need Edit03 icon
This commit
-  add Edit03 icon
> feat: add Edit03 icon

- packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- update dashboard chart legend click option
This commit
- update dashboard chart legend click option
> chore(toolkit): update dashboard chart legend click option

- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/model/useDeployModel.ts
- packages/toolkit/src/lib/react-query-service/model/useUnDeployModel.ts
- packages/toolkit/src/view/model/ChangeModelStateToggle.tsx
Because
- add loader to state change for model deploy and undeploy
This commit
- add loader to state change for model deploy and undeploy
> feat(toolkit): add loader to state change for model deploy and undeploy

- packages/toolkit/src/lib/dashboard/generateChartData.ts
- packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- update dashboard chart
This commit
- update dashboard chart
> chore(toolkit): update dashboard chart

- packages/toolkit/src/lib/dashboard/generateChartData.ts
- packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- update minInterval of y-axis
This commit
- update minInterval of y-axis
> fix(toolkit): update minInterval of y-axis

- packages/design-system/package.json
- packages/design-system/src/new-ui/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/new-ui/Dropdown/Dropdown.tsx
- packages/design-system/src/new-ui/Dropdown/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- add dropdown component
This commit
- add dropdown component
> feat(design-system): add dropdown component

- packages/design-system/src/new-ui/Icons/Menu01.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- add Menu icon
This commit
- add Menu icon
> feat(design-system): add Menu icon

- packages/design-system/src/new-ui/Icons/ArrowUpRight.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- add ArrowUpRight icon
This commit
- add ArrowUpRight icon
> feat(design-system): add ArrowUpRight icon

- packages/design-system/src/new-ui/Logos/Twitter.tsx
- packages/design-system/src/new-ui/Logos/index.ts
Because
- add twitter icon
This commit
- add twitter icon
> chore(design-system): add twitter icon

- packages/design-system/src/new-ui/Icons/CodeBrowser.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We need this icon
This commit
- add code browser icon
> chore: add code browser icon

- packages/design-system/src/ui/Icons/GoogleIcon/GoogleIcon.stories.tsx
- packages/design-system/src/ui/Icons/GoogleIcon/GoogleIcon.tsx
- packages/design-system/src/ui/Icons/GoogleIcon/index.ts
- packages/design-system/src/ui/Icons/index.ts
Because
- add google icon
This commit
- add google icon
> chore(design-system): add google icon

- packages/design-system/src/new-ui/ComplicateIcons/ComplicateIcons.stories.tsx
- packages/design-system/src/new-ui/ComplicateIcons/Doc.tsx
- packages/design-system/src/new-ui/ComplicateIcons/ImageToImage.tsx
- packages/design-system/src/new-ui/ComplicateIcons/ImageToText.tsx
- packages/design-system/src/new-ui/ComplicateIcons/Number.tsx
- packages/design-system/src/new-ui/ComplicateIcons/TextEmbedding.tsx
- packages/design-system/src/new-ui/ComplicateIcons/TextGeneration.tsx
- packages/design-system/src/new-ui/ComplicateIcons/TextToImage.tsx
- packages/design-system/src/new-ui/ComplicateIcons/ToggleLeft.tsx
- packages/design-system/src/new-ui/ComplicateIcons/index.ts
Because
- we need doc icon
This commit
- add doc icon and change display name of complicated icon
> feat: add doc icon and change display name of complicated icon

- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useConnectorTestModeOutputFields.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useEndOperatorTestModeOutputFields.tsx
Because
- we have object and object_array type
This commit
- support object and object_array
> feat: support object and object_array

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/lib/createInitialGraphData.tsx
Because
- data connector has issue about edit the input data
This commit
- fix data connector issue
> fix: fix data connector issue

- packages/design-system/src/new-ui/Popover/Popover.tsx
Because
- popover style has some color coming from shacdn
This commit
- fix popover style
> fix: fix popover style

- packages/toolkit/package.json
- packages/toolkit/src/lib/vdp-sdk/connector/queries.ts
- packages/toolkit/src/lib/vdp-sdk/metric/pipeline/queries.ts
- packages/toolkit/src/lib/vdp-sdk/model/queries.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- We need a place to display pipeline release information
This commit
- add pipelineRelease bottom bar
> feat: add pipelineRelease bottom bar

- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/pipeline/useCreateUserPipelineRelease.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/ReleasePipelineModal.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
Because
- We need to help user release the pipeline
This commit
- add the modal to help user release the pipeline
> feat(pipeline-builder): add the modal to help user release the pipeline

- packages/toolkit/package.json
- packages/toolkit/src/components/Topbar.tsx
- packages/toolkit/src/components/cells/Cell.tsx
- packages/toolkit/src/view/ResourcesTable.tsx
- packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx
- packages/toolkit/src/view/index.ts
- packages/toolkit/src/view/model/ModelHubCreatePageMainView.tsx
- packages/toolkit/src/view/model/ModelHubListPageMainView.tsx
- packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx
- packages/toolkit/src/view/model/ModelsTable.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
- packages/toolkit/src/view/pipeline-builder/components/ReleasePipelineModal.tsx
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
- packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/resource/ResourceListPageMainView.tsx
- packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- We are going to support pipeline recipe versioning
This commit
- user can release their saved pipeline in pipeline-builder
> feat(toolkit): user can release their saved pipeline in pipeline-builder

- packages/design-system/package.json
- packages/design-system/src/new-ui/Tabs/Tabs.stories.tsx
- packages/design-system/src/new-ui/Tabs/Tabs.tsx
- packages/design-system/src/new-ui/Tabs/index.ts
- packages/design-system/src/new-ui/index.ts
- pnpm-lock.yaml
Because
- We need Tabs to help us better display complex information
This commit
- add Tabs component
> feat(design-system): add Tabs component

- packages/design-system/src/new-ui/Combobox/Combobox.stories.tsx
- packages/design-system/src/new-ui/Combobox/Combobox.tsx
- packages/design-system/src/new-ui/Command/Command.stories.tsx
- packages/design-system/src/new-ui/DataTable/DataTable.stories.tsx
- packages/design-system/src/new-ui/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/new-ui/Tabs/Tabs.stories.tsx
- packages/design-system/src/ui-helpers/getModelInstanceTaskToolkit.tsx
Because
- We have lint issue in the design-system
This commit
- (fix lint issue in the design-system
> fix: fix lint issue in the design-system

- packages/toolkit/package.json
- packages/toolkit/src/components/CodeBlock.tsx
- packages/toolkit/src/components/CopyToClipboardButton.tsx
- packages/toolkit/src/components/index.ts
- packages/toolkit/src/lib/react-query-service/pipeline/useUserPipelineReleases.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitModal.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
Because
- User should be empowered to view the recipe directly
This commit
- user can directly view their pipelines recipe on the builder
> feat(toolkit): user can directly view their pipelines recipe on the builder

- packages/design-system/src/new-ui/Icons/Copy06.tsx
- packages/design-system/src/new-ui/Icons/index.ts
- packages/design-system/src/new-ui/Tabs/Tabs.tsx
Because
- We need copy06 icon
This commit
-  add copy06 icon and fix Tabs overflow issue
> feat: add copy06 icon and fix Tabs overflow issue

- packages/design-system/src/new-ui/ScrollArea/ScrollArea.stories.tsx
- packages/design-system/src/new-ui/ScrollArea/ScrollArea.tsx
- packages/design-system/src/new-ui/ScrollArea/index.ts
- packages/design-system/src/new-ui/index.ts
Because
- We need ScrollArea
This commit
- add ScrollArea
> feat(design-system): add ScrollArea

- packages/toolkit/package.json
- packages/toolkit/src/components/CodeBlock.tsx
- packages/toolkit/src/components/CopyToClipboardButton.tsx
- packages/toolkit/src/components/index.ts
- packages/toolkit/src/lib/react-query-service/pipeline/useUserPipelineReleases.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitModal.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
Because
- Empower use to better navigate the pipeline
This commit
- user can view the pipeline's recipe on pipeline builder
> feat(toolkit): user can view the pipeline's recipe on pipeline builder

- packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts
- packages/toolkit/src/lib/vdp-sdk/mgmt/index.ts
- packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts
Because
- We are going to support simple auth in instill-core
This commit
- add auth related endpoint
> feat(toolkit): add auth related endpoint

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
Because
- user can easily identify the selected node
This commit
- user can easily identify the selected node
> feat(toolkit): user can easily identify the selected node

- packages/toolkit/package.json
- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/view/ai/AIResourceForm.tsx
- packages/toolkit/src/view/blockchain/BlockchainResourceForm.tsx
- packages/toolkit/src/view/data/DataResourceForm.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/AddConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/InputPropertyItem.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/FieldRoot.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ImagesField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
- packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
- packages/toolkit/src/view/resource/ResourceListPageMainView.tsx
- packages/toolkit/src/view/resource/ResourceSettingPageMainView.tsx
Because
- Node is currently too small
This commit
- user will have 1.5x wider node under normal mode and 2.0x wider
> feat(toolkit): user will have 1.5x wider node under normal mode and 2.0x wider

- packages/toolkit/package.json
- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/lib/vdp-sdk/connector/types.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
- packages/toolkit/src/view/ai/AIResourceForm.tsx
- packages/toolkit/src/view/blockchain/BlockchainResourceForm.tsx
- packages/toolkit/src/view/data/DataResourceForm.tsx
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
- packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipe.tsx
- packages/toolkit/src/view/pipeline-builder/lib/createInitialGraphData.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
- packages/toolkit/src/view/resource/AddConnectorResourceDialog.tsx
- packages/toolkit/src/view/resource/ResourceListPageMainView.tsx
Because
- Improve UX and enable template engine
This commit
- user can have node with uncreated resource on pipeline builder
> feat(toolkit): user can have node with uncreated resource on pipeline builder

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/EmptyNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/StartNode.tsx
- packages/toolkit/src/view/pipeline-builder/lib/createInitialGraphData.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- Support version control
This commit
- user can view different release versions on pipeline builder
> feat(toolkit): user can view different release versions on pipeline builder

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/StartNode.tsx
Because
- Improve UX
This commit
- User can now have a centralize control panel to copy, delete and configure node
> feat(toolkit): User can now have a centralize control panel to copy, delete and configure node

- packages/design-system/src/new-ui/Command/Command.tsx
Because
- The command component's style is wrong
This commit
- fix command style
> fix(design-system): fix command style

- packages/design-system/src/new-ui/Dialog/Dialog.tsx
Because
- The max-w of Dialog is too small 
This commit
- increase the limit of DialogContent
> chore(design-system): increase the limit of DialogContent

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/components/template/FullTemplatesCommand.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/StaffPickTemplates.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/TemplateCard.tsx
Because
- Improve UX
This commit
- user can have a centralize command to view all the templates
> feat(toolkit): user can have a centralize command to view all the templates

- packages/design-system/src/new-ui/Icons/Lock03.tsx
- packages/design-system/src/new-ui/Icons/LockUnlocked03.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We need these icons
This commit
- add lock related icons
> feat(design-system): add lock related icons

- packages/design-system/src/new-ui/Icons/Link01.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We need link icon
This commit
- add Link icon
> feat(design-system): add Link icon

- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
- packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
Because
- Let user share their pipeline
This commit
-  User can toggle their pipelines permission level
> feat(toolkit): User can toggle their pipelines permission level

- packages/toolkit/package.json
- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx
Because
- empower user to share their pipeline
This commit
- user can share their private pipeline with share by link feature
> feat(toolkit): user can share their private pipeline with share by link feature

- packages/toolkit/package.json
- packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx
Because
- (write the reason why we need to consider this PR in a list)
This commit
- (write the summary of all commits in this PR in a list)
> feat: user can share their private pipeline with specific link

- packages/toolkit/package.json
- packages/toolkit/src/lib/react-query-service/pipeline/useUserPipeline.ts
- packages/toolkit/src/lib/react-query-service/pipeline/useUserPipelineReleases.ts
- packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/StartNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/StaffPickTemplates.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
- pnpm-lock.yaml
Because
- empower user to share their pipeline
This commit
- Non owner user can view public pipeline or pipeline that is shared by link
> feat(toolkit): Non owner user can view public pipeline or pipeline that is shared by link

- packages/toolkit/package.json
- packages/toolkit/src/view/ai/AIResourceForm.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipe.tsx
- packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- Empower user to share
This commit
- user can clone other users shared pipelines
> feat(toolkit): user can clone other users shared pipelines

- packages/toolkit/package.json
- packages/toolkit/src/view/index.ts
- packages/toolkit/src/view/mgmt/ConfigureProfileForm/ConfigureProfileControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitModal.tsx
- packages/toolkit/src/view/user-settings/ProfileTab.tsx
- packages/toolkit/src/view/user-settings/SettingsPageView.tsx
- packages/toolkit/src/view/user-settings/TabBase.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/APITokenNameCell.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/APITokenTab.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/APITokenTable.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/CreateAPITokenDialog.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/DeleteAPITokenDialog.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/index.ts
- packages/toolkit/src/view/user-settings/billing-tab/BillingCard.tsx
- packages/toolkit/src/view/user-settings/billing-tab/BillingTab.tsx
- packages/toolkit/src/view/user-settings/billing-tab/SubscriptionStatusLabel.tsx
- packages/toolkit/src/view/user-settings/billing-tab/index.ts
- packages/toolkit/src/view/user-settings/index.ts
- pnpm-lock.yaml
Because
- centralize component
This commit
- add user-setting related page into toolkit
> feat(toolkit): add user-setting related page into toolkit

- packages/toolkit/src/view/pipeline-builder/components/triggerPipelineSnippets.ts
Because
- pipeline trigger snippet is wrong
This commit
- fix the wrong pipeline trigger snippet
> fix(toolkit): fix the wrong pipeline trigger snippet

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialogItem.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
Because
- improve UX
This commit
- user should be able to choose existing resource for nodes in pipeline created from template
> feat(toolkit): user should be able to choose existing resource for nodes in pipeline created from template

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/index.ts
- packages/toolkit/src/view/pipeline-builder/lib/index.ts
- packages/toolkit/src/view/pipeline-builder/lib/useSortedReleases.tsx
- packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts
- pnpm-lock.yaml
Because
- improve UX
This commit
- user can better identify whether current view is latest releases
> feat: user can better identify whether current view is latest releases

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
Because
- Back to latest version should update node values
This commit
- fix back to latest version button wont update nodes input value
> fix: fix back to latest version button wont update nodes input value

- packages/toolkit/package.json
- packages/toolkit/src/components/CopyToClipboardButton.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/FieldRoot.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useEndOperatorTestModeOutputFields.tsx
Because
- Improve UX 
This commit
- user can have pre-formatted text field to better visualize output
> feat(toolkit): user can have pre-formatted text field to better visualize output

- packages/toolkit/package.json
- packages/toolkit/src/components/CopyToClipboardButton.tsx
- packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/StaffPickTemplates.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/TemplateCard.tsx
- packages/toolkit/src/view/pipeline-builder/lib/templates.ts
- packages/toolkit/src/view/user-settings/api-token-tab/APITokenTab.tsx
- packages/toolkit/src/view/user-settings/api-token-tab/DeleteAPITokenDialog.tsx
Because
- improve UX
This commit
- User can have more templates to have better guidance
> feat(pipeline-builder): User can have more templates to have better guidance

- packages/toolkit/package.json
- packages/toolkit/src/view/ai/AIForm.tsx
- packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx
- packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx
Because
- improve UX
This commit
- user can better identify how to fill in instill model component configuration
> feat(toolkit): user can better identify how to fill in instill model component configuration

- packages/toolkit/src/view/ai/AIForm.tsx
- packages/toolkit/src/view/blockchain/BlockchainForm.tsx
- packages/toolkit/src/view/pipeline-builder/RightPanel.tsx
Because
- improve UX
This commit
- user can better identify his configuration on pipeline builder right panel is finished
> feat(toolkit): user can better identify his configuration on pipeline builder right panel is finished

- packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts
Because
- schema parsing error on Pinecone, Bigquery and GCS cause console to crash
This commit
- fix schema parsing error on Pinecone, Bigquery and GCS cause console to crash
> fix(toolkit): fix schema parsing error on Pinecone, Bigquery and GCS cause console to crash

- packages/design-system/src/new-ui/Icons/DotsVertical.tsx
- packages/design-system/src/new-ui/Icons/index.ts
Because
- We need this icon for upcoming feature
This commit
- add DotsVertical icon
> chore(design-system): add DotsVertical icon

- packages/toolkit/package.json
- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/view/pipeline-builder/lib/getRawPipelineRecipeFromPipelineRecipe.ts
- packages/toolkit/src/view/pipeline-builder/lib/index.ts
- packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
- packages/toolkit/src/view/pipeline/PipelineTableMenu.tsx
- packages/toolkit/src/view/pipeline/PipelinesTable.tsx
- packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- Improve the UX
This commit
- user can duplicate the pipeline they owned
> feat(cortex): user can duplicate the pipeline they owned

- packages/design-system/src/new-ui/Input/Input.stories.tsx
Because
- auto-resize input is good for our UX
This commit
- add story about how to build the autoresize input
> chore(design-system): add story about how to build the autoresize input

- packages/toolkit/package.json
- packages/toolkit/src/components/AutoresizeInput.tsx
- packages/toolkit/src/components/ImageWithFallback.tsx
- packages/toolkit/src/components/Topbar.tsx
- packages/toolkit/src/components/index.ts
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/ConnectorNode/ConnectorNodeControlPanel.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
Because
- Improve UX
This commit
- User can have autoresize input when edit node and pipeline name
> feat(toolkit): User can have autoresize input when edit node and pipeline name

- packages/toolkit/package.json
- packages/toolkit/src/components/GeneralDeleteResourceModal.tsx
- packages/toolkit/src/components/WarnUnsavedChangesModal.tsx
- packages/toolkit/src/view/ai/AIResourceForm.tsx
- packages/toolkit/src/view/blockchain/BlockchainResourceForm.tsx
- packages/toolkit/src/view/data/DataResourceForm.tsx
- packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
- packages/toolkit/src/view/pipeline-builder/components/ReleasePipelineModal.tsx
- packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx
Because
- Improve UX
This commit
- User can better identify the process is still running when doing actions
> feat(toolkit): User can better identify the process is still running when doing actions

- packages/toolkit/package.json
- packages/toolkit/src/view/data/DataComponentForm.tsx
- packages/toolkit/src/view/pipeline-builder/Flow.tsx
- packages/toolkit/src/view/pipeline-builder/components/CustomEdge.tsx
Because
- improve UX
This commit
- User will have cleaner canvas by introducing smooth-edge edges
> feat(pipeline-builder): User can have cleaner canvas by introducing smooth-edge edges

- packages/toolkit/package.json
- packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
- packages/toolkit/src/view/pipeline-builder/components/ReleasePipelineModal.tsx
- packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/ResourceIDTag.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-input-fields/NumbersField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-input-fields/TextsField.tsx
Because
- Improve UX
This commit
- Make the array fields on start node start with only one field
> feat(pipeline-builder): Make the array fields on start node start with only one field

- packages/toolkit/package.json
- packages/toolkit/src/view/data/DataComponentForm.tsx
- packages/toolkit/src/view/data/DataResourceForm.tsx
- packages/toolkit/src/view/pipeline-builder/RightPanel.tsx
- packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNodeControlPanel.tsx
- packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/TemplateCard.tsx
- packages/toolkit/src/view/pipeline-builder/lib/extractPipelineComponentReferenceFromString.ts
- packages/toolkit/src/view/pipeline-builder/lib/extractTemplateReferenceSetFromString.ts
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useConnectorTestModeOutputFields.tsx
- packages/toolkit/src/view/resource/AddConnectorResourceDialog.tsx
- packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- console doesn't correctly handle boolean value on pipeline builder
This commit
- fix console doesn't correctly handle boolean value on pipeline builder
> fix(toolkit): fix console doesn't correctly handle boolean value on pipeline builder

- packages/toolkit/package.json
- packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/DataConnectorFreeForm.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/InputProperties.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/OutputProperties.tsx
- packages/toolkit/src/view/pipeline-builder/components/template/TemplateCard.tsx
Because
- data connector can't correctly display the free-form's value
This commit
- fix data connector can't correctly display the free-form's value
> fix(pipeline-builder): fix data connector can't correctly display the free-form's value

- packages/toolkit/package.json
- packages/toolkit/src/view/data/DataComponentForm.tsx
- packages/toolkit/src/view/pipeline-builder/components/connector-node/InputPropertyItem.tsx
- packages/toolkit/src/view/pipeline-builder/lib/recursiveTransformToString.ts
- packages/toolkit/src/view/pipeline-builder/lib/templates.ts
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx
- packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx
Because
- fix boolean issue among the pipeline-builder form
This commit
- fix boolean issue among the pipeline-builder form
> fix(toolkit): fix boolean issue
